// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: admin/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_ValidateAdminToken_FullMethodName    = "/admin.AdminService/ValidateAdminToken"
	AdminService_GetAdminProfile_FullMethodName       = "/admin.AdminService/GetAdminProfile"
	AdminService_CheckAdminPermission_FullMethodName  = "/admin.AdminService/CheckAdminPermission"
	AdminService_ListDrivers_FullMethodName           = "/admin.AdminService/ListDrivers"
	AdminService_GetDriver_FullMethodName             = "/admin.AdminService/GetDriver"
	AdminService_ApproveDriver_FullMethodName         = "/admin.AdminService/ApproveDriver"
	AdminService_RejectDriver_FullMethodName          = "/admin.AdminService/RejectDriver"
	AdminService_SuspendDriver_FullMethodName         = "/admin.AdminService/SuspendDriver"
	AdminService_ActivateDriver_FullMethodName        = "/admin.AdminService/ActivateDriver"
	AdminService_GetDriverDocuments_FullMethodName    = "/admin.AdminService/GetDriverDocuments"
	AdminService_ApproveDriverDocument_FullMethodName = "/admin.AdminService/ApproveDriverDocument"
	AdminService_RejectDriverDocument_FullMethodName  = "/admin.AdminService/RejectDriverDocument"
	AdminService_DeleteDriver_FullMethodName          = "/admin.AdminService/DeleteDriver"
	AdminService_ListDriverDocuments_FullMethodName   = "/admin.AdminService/ListDriverDocuments"
	AdminService_GetDriverDocument_FullMethodName     = "/admin.AdminService/GetDriverDocument"
	AdminService_DeleteDriverDocument_FullMethodName  = "/admin.AdminService/DeleteDriverDocument"
	AdminService_GetEnum_FullMethodName               = "/admin.AdminService/GetEnum"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ======= Service Definition =======
type AdminServiceClient interface {
	// Validate admin token
	ValidateAdminToken(ctx context.Context, in *RqValidateAdminToken, opts ...grpc.CallOption) (*RsValidateAdminToken, error)
	// Get admin profile
	GetAdminProfile(ctx context.Context, in *RqGetAdminProfile, opts ...grpc.CallOption) (*RsGetAdminProfile, error)
	// Check admin permissions
	CheckAdminPermission(ctx context.Context, in *RqCheckAdminPermission, opts ...grpc.CallOption) (*RsCheckAdminPermission, error)
	// Driver management
	ListDrivers(ctx context.Context, in *RqListDrivers, opts ...grpc.CallOption) (*RsListDrivers, error)
	GetDriver(ctx context.Context, in *RqGetDriver, opts ...grpc.CallOption) (*RsGetDriver, error)
	ApproveDriver(ctx context.Context, in *RqApproveDriver, opts ...grpc.CallOption) (*RsApproveDriver, error)
	RejectDriver(ctx context.Context, in *RqRejectDriver, opts ...grpc.CallOption) (*RsRejectDriver, error)
	SuspendDriver(ctx context.Context, in *RqSuspendDriver, opts ...grpc.CallOption) (*RsSuspendDriver, error)
	ActivateDriver(ctx context.Context, in *RqActivateDriver, opts ...grpc.CallOption) (*RsActivateDriver, error)
	GetDriverDocuments(ctx context.Context, in *RqGetDriverDocuments, opts ...grpc.CallOption) (*RsGetDriverDocuments, error)
	ApproveDriverDocument(ctx context.Context, in *RqApproveDriverDocument, opts ...grpc.CallOption) (*RsApproveDriverDocument, error)
	RejectDriverDocument(ctx context.Context, in *RqRejectDriverDocument, opts ...grpc.CallOption) (*RsRejectDriverDocument, error)
	DeleteDriver(ctx context.Context, in *RqDeleteDriver, opts ...grpc.CallOption) (*RsDeleteDriver, error)
	// Driver document management
	ListDriverDocuments(ctx context.Context, in *RqListDriverDocuments, opts ...grpc.CallOption) (*RsListDriverDocuments, error)
	GetDriverDocument(ctx context.Context, in *RqGetDriverDocument, opts ...grpc.CallOption) (*RsGetDriverDocument, error)
	DeleteDriverDocument(ctx context.Context, in *RqDeleteDriverDocument, opts ...grpc.CallOption) (*RsDeleteDriverDocument, error)
	// Enum management
	GetEnum(ctx context.Context, in *RqGetEnum, opts ...grpc.CallOption) (*RsGetEnum, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) ValidateAdminToken(ctx context.Context, in *RqValidateAdminToken, opts ...grpc.CallOption) (*RsValidateAdminToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsValidateAdminToken)
	err := c.cc.Invoke(ctx, AdminService_ValidateAdminToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetAdminProfile(ctx context.Context, in *RqGetAdminProfile, opts ...grpc.CallOption) (*RsGetAdminProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetAdminProfile)
	err := c.cc.Invoke(ctx, AdminService_GetAdminProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CheckAdminPermission(ctx context.Context, in *RqCheckAdminPermission, opts ...grpc.CallOption) (*RsCheckAdminPermission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsCheckAdminPermission)
	err := c.cc.Invoke(ctx, AdminService_CheckAdminPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListDrivers(ctx context.Context, in *RqListDrivers, opts ...grpc.CallOption) (*RsListDrivers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsListDrivers)
	err := c.cc.Invoke(ctx, AdminService_ListDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDriver(ctx context.Context, in *RqGetDriver, opts ...grpc.CallOption) (*RsGetDriver, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetDriver)
	err := c.cc.Invoke(ctx, AdminService_GetDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ApproveDriver(ctx context.Context, in *RqApproveDriver, opts ...grpc.CallOption) (*RsApproveDriver, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsApproveDriver)
	err := c.cc.Invoke(ctx, AdminService_ApproveDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RejectDriver(ctx context.Context, in *RqRejectDriver, opts ...grpc.CallOption) (*RsRejectDriver, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsRejectDriver)
	err := c.cc.Invoke(ctx, AdminService_RejectDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SuspendDriver(ctx context.Context, in *RqSuspendDriver, opts ...grpc.CallOption) (*RsSuspendDriver, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsSuspendDriver)
	err := c.cc.Invoke(ctx, AdminService_SuspendDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ActivateDriver(ctx context.Context, in *RqActivateDriver, opts ...grpc.CallOption) (*RsActivateDriver, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsActivateDriver)
	err := c.cc.Invoke(ctx, AdminService_ActivateDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDriverDocuments(ctx context.Context, in *RqGetDriverDocuments, opts ...grpc.CallOption) (*RsGetDriverDocuments, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetDriverDocuments)
	err := c.cc.Invoke(ctx, AdminService_GetDriverDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ApproveDriverDocument(ctx context.Context, in *RqApproveDriverDocument, opts ...grpc.CallOption) (*RsApproveDriverDocument, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsApproveDriverDocument)
	err := c.cc.Invoke(ctx, AdminService_ApproveDriverDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RejectDriverDocument(ctx context.Context, in *RqRejectDriverDocument, opts ...grpc.CallOption) (*RsRejectDriverDocument, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsRejectDriverDocument)
	err := c.cc.Invoke(ctx, AdminService_RejectDriverDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteDriver(ctx context.Context, in *RqDeleteDriver, opts ...grpc.CallOption) (*RsDeleteDriver, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsDeleteDriver)
	err := c.cc.Invoke(ctx, AdminService_DeleteDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListDriverDocuments(ctx context.Context, in *RqListDriverDocuments, opts ...grpc.CallOption) (*RsListDriverDocuments, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsListDriverDocuments)
	err := c.cc.Invoke(ctx, AdminService_ListDriverDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDriverDocument(ctx context.Context, in *RqGetDriverDocument, opts ...grpc.CallOption) (*RsGetDriverDocument, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetDriverDocument)
	err := c.cc.Invoke(ctx, AdminService_GetDriverDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteDriverDocument(ctx context.Context, in *RqDeleteDriverDocument, opts ...grpc.CallOption) (*RsDeleteDriverDocument, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsDeleteDriverDocument)
	err := c.cc.Invoke(ctx, AdminService_DeleteDriverDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetEnum(ctx context.Context, in *RqGetEnum, opts ...grpc.CallOption) (*RsGetEnum, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetEnum)
	err := c.cc.Invoke(ctx, AdminService_GetEnum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// ======= Service Definition =======
type AdminServiceServer interface {
	// Validate admin token
	ValidateAdminToken(context.Context, *RqValidateAdminToken) (*RsValidateAdminToken, error)
	// Get admin profile
	GetAdminProfile(context.Context, *RqGetAdminProfile) (*RsGetAdminProfile, error)
	// Check admin permissions
	CheckAdminPermission(context.Context, *RqCheckAdminPermission) (*RsCheckAdminPermission, error)
	// Driver management
	ListDrivers(context.Context, *RqListDrivers) (*RsListDrivers, error)
	GetDriver(context.Context, *RqGetDriver) (*RsGetDriver, error)
	ApproveDriver(context.Context, *RqApproveDriver) (*RsApproveDriver, error)
	RejectDriver(context.Context, *RqRejectDriver) (*RsRejectDriver, error)
	SuspendDriver(context.Context, *RqSuspendDriver) (*RsSuspendDriver, error)
	ActivateDriver(context.Context, *RqActivateDriver) (*RsActivateDriver, error)
	GetDriverDocuments(context.Context, *RqGetDriverDocuments) (*RsGetDriverDocuments, error)
	ApproveDriverDocument(context.Context, *RqApproveDriverDocument) (*RsApproveDriverDocument, error)
	RejectDriverDocument(context.Context, *RqRejectDriverDocument) (*RsRejectDriverDocument, error)
	DeleteDriver(context.Context, *RqDeleteDriver) (*RsDeleteDriver, error)
	// Driver document management
	ListDriverDocuments(context.Context, *RqListDriverDocuments) (*RsListDriverDocuments, error)
	GetDriverDocument(context.Context, *RqGetDriverDocument) (*RsGetDriverDocument, error)
	DeleteDriverDocument(context.Context, *RqDeleteDriverDocument) (*RsDeleteDriverDocument, error)
	// Enum management
	GetEnum(context.Context, *RqGetEnum) (*RsGetEnum, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) ValidateAdminToken(context.Context, *RqValidateAdminToken) (*RsValidateAdminToken, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAdminToken not implemented")
}
func (UnimplementedAdminServiceServer) GetAdminProfile(context.Context, *RqGetAdminProfile) (*RsGetAdminProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminProfile not implemented")
}
func (UnimplementedAdminServiceServer) CheckAdminPermission(context.Context, *RqCheckAdminPermission) (*RsCheckAdminPermission, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAdminPermission not implemented")
}
func (UnimplementedAdminServiceServer) ListDrivers(context.Context, *RqListDrivers) (*RsListDrivers, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrivers not implemented")
}
func (UnimplementedAdminServiceServer) GetDriver(context.Context, *RqGetDriver) (*RsGetDriver, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriver not implemented")
}
func (UnimplementedAdminServiceServer) ApproveDriver(context.Context, *RqApproveDriver) (*RsApproveDriver, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveDriver not implemented")
}
func (UnimplementedAdminServiceServer) RejectDriver(context.Context, *RqRejectDriver) (*RsRejectDriver, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectDriver not implemented")
}
func (UnimplementedAdminServiceServer) SuspendDriver(context.Context, *RqSuspendDriver) (*RsSuspendDriver, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendDriver not implemented")
}
func (UnimplementedAdminServiceServer) ActivateDriver(context.Context, *RqActivateDriver) (*RsActivateDriver, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateDriver not implemented")
}
func (UnimplementedAdminServiceServer) GetDriverDocuments(context.Context, *RqGetDriverDocuments) (*RsGetDriverDocuments, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverDocuments not implemented")
}
func (UnimplementedAdminServiceServer) ApproveDriverDocument(context.Context, *RqApproveDriverDocument) (*RsApproveDriverDocument, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveDriverDocument not implemented")
}
func (UnimplementedAdminServiceServer) RejectDriverDocument(context.Context, *RqRejectDriverDocument) (*RsRejectDriverDocument, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectDriverDocument not implemented")
}
func (UnimplementedAdminServiceServer) DeleteDriver(context.Context, *RqDeleteDriver) (*RsDeleteDriver, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDriver not implemented")
}
func (UnimplementedAdminServiceServer) ListDriverDocuments(context.Context, *RqListDriverDocuments) (*RsListDriverDocuments, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDriverDocuments not implemented")
}
func (UnimplementedAdminServiceServer) GetDriverDocument(context.Context, *RqGetDriverDocument) (*RsGetDriverDocument, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverDocument not implemented")
}
func (UnimplementedAdminServiceServer) DeleteDriverDocument(context.Context, *RqDeleteDriverDocument) (*RsDeleteDriverDocument, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDriverDocument not implemented")
}
func (UnimplementedAdminServiceServer) GetEnum(context.Context, *RqGetEnum) (*RsGetEnum, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnum not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_ValidateAdminToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqValidateAdminToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ValidateAdminToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ValidateAdminToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ValidateAdminToken(ctx, req.(*RqValidateAdminToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetAdminProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetAdminProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetAdminProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetAdminProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetAdminProfile(ctx, req.(*RqGetAdminProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CheckAdminPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqCheckAdminPermission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CheckAdminPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CheckAdminPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CheckAdminPermission(ctx, req.(*RqCheckAdminPermission))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqListDrivers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListDrivers(ctx, req.(*RqListDrivers))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetDriver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDriver(ctx, req.(*RqGetDriver))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ApproveDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqApproveDriver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ApproveDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ApproveDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ApproveDriver(ctx, req.(*RqApproveDriver))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RejectDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqRejectDriver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RejectDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RejectDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RejectDriver(ctx, req.(*RqRejectDriver))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SuspendDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqSuspendDriver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SuspendDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SuspendDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SuspendDriver(ctx, req.(*RqSuspendDriver))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ActivateDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqActivateDriver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ActivateDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ActivateDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ActivateDriver(ctx, req.(*RqActivateDriver))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDriverDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetDriverDocuments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDriverDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDriverDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDriverDocuments(ctx, req.(*RqGetDriverDocuments))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ApproveDriverDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqApproveDriverDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ApproveDriverDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ApproveDriverDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ApproveDriverDocument(ctx, req.(*RqApproveDriverDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RejectDriverDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqRejectDriverDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RejectDriverDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RejectDriverDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RejectDriverDocument(ctx, req.(*RqRejectDriverDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqDeleteDriver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteDriver(ctx, req.(*RqDeleteDriver))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListDriverDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqListDriverDocuments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListDriverDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListDriverDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListDriverDocuments(ctx, req.(*RqListDriverDocuments))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDriverDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetDriverDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDriverDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDriverDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDriverDocument(ctx, req.(*RqGetDriverDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteDriverDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqDeleteDriverDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteDriverDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteDriverDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteDriverDocument(ctx, req.(*RqDeleteDriverDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetEnum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetEnum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetEnum(ctx, req.(*RqGetEnum))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAdminToken",
			Handler:    _AdminService_ValidateAdminToken_Handler,
		},
		{
			MethodName: "GetAdminProfile",
			Handler:    _AdminService_GetAdminProfile_Handler,
		},
		{
			MethodName: "CheckAdminPermission",
			Handler:    _AdminService_CheckAdminPermission_Handler,
		},
		{
			MethodName: "ListDrivers",
			Handler:    _AdminService_ListDrivers_Handler,
		},
		{
			MethodName: "GetDriver",
			Handler:    _AdminService_GetDriver_Handler,
		},
		{
			MethodName: "ApproveDriver",
			Handler:    _AdminService_ApproveDriver_Handler,
		},
		{
			MethodName: "RejectDriver",
			Handler:    _AdminService_RejectDriver_Handler,
		},
		{
			MethodName: "SuspendDriver",
			Handler:    _AdminService_SuspendDriver_Handler,
		},
		{
			MethodName: "ActivateDriver",
			Handler:    _AdminService_ActivateDriver_Handler,
		},
		{
			MethodName: "GetDriverDocuments",
			Handler:    _AdminService_GetDriverDocuments_Handler,
		},
		{
			MethodName: "ApproveDriverDocument",
			Handler:    _AdminService_ApproveDriverDocument_Handler,
		},
		{
			MethodName: "RejectDriverDocument",
			Handler:    _AdminService_RejectDriverDocument_Handler,
		},
		{
			MethodName: "DeleteDriver",
			Handler:    _AdminService_DeleteDriver_Handler,
		},
		{
			MethodName: "ListDriverDocuments",
			Handler:    _AdminService_ListDriverDocuments_Handler,
		},
		{
			MethodName: "GetDriverDocument",
			Handler:    _AdminService_GetDriverDocument_Handler,
		},
		{
			MethodName: "DeleteDriverDocument",
			Handler:    _AdminService_DeleteDriverDocument_Handler,
		},
		{
			MethodName: "GetEnum",
			Handler:    _AdminService_GetEnum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/admin.proto",
}
