// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum value representation
type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Enum) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Enum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enum) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Enum) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Enum response
type EnumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enum          []*Enum                `protobuf:"bytes,1,rep,name=enum,proto3" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumResponse) Reset() {
	*x = EnumResponse{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumResponse) ProtoMessage() {}

func (x *EnumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumResponse.ProtoReflect.Descriptor instead.
func (*EnumResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *EnumResponse) GetEnum() []*Enum {
	if x != nil {
		return x.Enum
	}
	return nil
}

type EnumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnumType      string                 `protobuf:"bytes,1,opt,name=enum_type,json=enumType,proto3" json:"enum_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumRequest) Reset() {
	*x = EnumRequest{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumRequest) ProtoMessage() {}

func (x *EnumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumRequest.ProtoReflect.Descriptor instead.
func (*EnumRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *EnumRequest) GetEnumType() string {
	if x != nil {
		return x.EnumType
	}
	return ""
}

type SendOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"` // e.g., "+91"
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`                                // e.g., "1234567890"
	Role          *EnumRequest           `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                                  // rider or driver
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpRequest) Reset() {
	*x = SendOtpRequest{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpRequest) ProtoMessage() {}

func (x *SendOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpRequest.ProtoReflect.Descriptor instead.
func (*SendOtpRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SendOtpRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *SendOtpRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendOtpRequest) GetRole() *EnumRequest {
	if x != nil {
		return x.Role
	}
	return nil
}

type SendOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"` // true if OTP was sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpResponse) Reset() {
	*x = SendOtpResponse{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpResponse) ProtoMessage() {}

func (x *SendOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpResponse.ProtoReflect.Descriptor instead.
func (*SendOtpResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SendOtpResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

type VerifyOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"` // OTP code
	Role          *EnumRequest           `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOtpRequest) Reset() {
	*x = VerifyOtpRequest{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOtpRequest) ProtoMessage() {}

func (x *VerifyOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOtpRequest.ProtoReflect.Descriptor instead.
func (*VerifyOtpRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyOtpRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *VerifyOtpRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifyOtpRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyOtpRequest) GetRole() *EnumRequest {
	if x != nil {
		return x.Role
	}
	return nil
}

type VerifyOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpSent       bool                   `protobuf:"varint,1,opt,name=otp_sent,json=otpSent,proto3" json:"otp_sent,omitempty"`
	UserAvailable bool                   `protobuf:"varint,2,opt,name=user_available,json=userAvailable,proto3" json:"user_available,omitempty"` // true if user exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOtpResponse) Reset() {
	*x = VerifyOtpResponse{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOtpResponse) ProtoMessage() {}

func (x *VerifyOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOtpResponse.ProtoReflect.Descriptor instead.
func (*VerifyOtpResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyOtpResponse) GetOtpSent() bool {
	if x != nil {
		return x.OtpSent
	}
	return false
}

func (x *VerifyOtpResponse) GetUserAvailable() bool {
	if x != nil {
		return x.UserAvailable
	}
	return false
}

type GoogleAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Role          *EnumRequest           `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleAuthRequest) Reset() {
	*x = GoogleAuthRequest{}
	mi := &file_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleAuthRequest) ProtoMessage() {}

func (x *GoogleAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleAuthRequest.ProtoReflect.Descriptor instead.
func (*GoogleAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GoogleAuthRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *GoogleAuthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GoogleAuthRequest) GetRole() *EnumRequest {
	if x != nil {
		return x.Role
	}
	return nil
}

type GoogleAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleAuthResponse) Reset() {
	*x = GoogleAuthResponse{}
	mi := &file_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleAuthResponse) ProtoMessage() {}

func (x *GoogleAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleAuthResponse.ProtoReflect.Descriptor instead.
func (*GoogleAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GoogleAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GoogleAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ParseTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTokenRequest) Reset() {
	*x = ParseTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTokenRequest) ProtoMessage() {}

func (x *ParseTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTokenRequest.ProtoReflect.Descriptor instead.
func (*ParseTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ParseTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ParseTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          *EnumResponse          `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"` // seconds since epoch
	Valid         bool                   `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTokenResponse) Reset() {
	*x = ParseTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTokenResponse) ProtoMessage() {}

func (x *ParseTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTokenResponse.ProtoReflect.Descriptor instead.
func (*ParseTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ParseTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParseTokenResponse) GetRole() *EnumResponse {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *ParseTokenResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *ParseTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type UserAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          *EnumRequest           `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthRequest) Reset() {
	*x = UserAuthRequest{}
	mi := &file_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthRequest) ProtoMessage() {}

func (x *UserAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthRequest.ProtoReflect.Descriptor instead.
func (*UserAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *UserAuthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAuthRequest) GetRole() *EnumRequest {
	if x != nil {
		return x.Role
	}
	return nil
}

type UserAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *TokenResponse         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthResponse) Reset() {
	*x = UserAuthResponse{}
	mi := &file_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthResponse) ProtoMessage() {}

func (x *UserAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthResponse.ProtoReflect.Descriptor instead.
func (*UserAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *UserAuthResponse) GetToken() *TokenResponse {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\"Z\n" +
	"\x04Enum\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\".\n" +
	"\fEnumResponse\x12\x1e\n" +
	"\x04enum\x18\x01 \x03(\v2\n" +
	".auth.EnumR\x04enum\"*\n" +
	"\vEnumRequest\x12\x1b\n" +
	"\tenum_type\x18\x01 \x01(\tR\benumType\"p\n" +
	"\x0eSendOtpRequest\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12%\n" +
	"\x04role\x18\x03 \x01(\v2\x11.auth.EnumRequestR\x04role\"%\n" +
	"\x0fSendOtpResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent\"\x86\x01\n" +
	"\x10VerifyOtpRequest\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12%\n" +
	"\x04role\x18\x04 \x01(\v2\x11.auth.EnumRequestR\x04role\"U\n" +
	"\x11VerifyOtpResponse\x12\x19\n" +
	"\botp_sent\x18\x01 \x01(\bR\aotpSent\x12%\n" +
	"\x0euser_available\x18\x02 \x01(\bR\ruserAvailable\"r\n" +
	"\x11GoogleAuthRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12%\n" +
	"\x04role\x18\x03 \x01(\v2\x11.auth.EnumRequestR\x04role\"\\\n" +
	"\x12GoogleAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"W\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\")\n" +
	"\x11ParseTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x93\x01\n" +
	"\x12ParseTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x04role\x18\x02 \x01(\v2\x12.auth.EnumResponseR\x04role\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12\x14\n" +
	"\x05valid\x18\x04 \x01(\bR\x05valid\"Q\n" +
	"\x0fUserAuthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x04role\x18\x02 \x01(\v2\x11.auth.EnumRequestR\x04role\"=\n" +
	"\x10UserAuthResponse\x12)\n" +
	"\x05token\x18\x01 \x01(\v2\x13.auth.TokenResponseR\x05token2\xd2\x03\n" +
	"\vAuthService\x128\n" +
	"\aSendOTP\x12\x14.auth.SendOtpRequest\x1a\x15.auth.SendOtpResponse\"\x00\x12>\n" +
	"\tVerifyOTP\x12\x16.auth.VerifyOtpRequest\x1a\x17.auth.VerifyOtpResponse\"\x00\x12C\n" +
	"\fGoogleSignup\x12\x17.auth.GoogleAuthRequest\x1a\x18.auth.GoogleAuthResponse\"\x00\x12B\n" +
	"\vGoogleLogin\x12\x17.auth.GoogleAuthRequest\x1a\x18.auth.GoogleAuthResponse\"\x00\x12@\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x13.auth.TokenResponse\"\x00\x12A\n" +
	"\n" +
	"ParseToken\x12\x17.auth.ParseTokenRequest\x1a\x18.auth.ParseTokenResponse\"\x00\x12;\n" +
	"\bUserAuth\x12\x15.auth.UserAuthRequest\x1a\x16.auth.UserAuthResponse\"\x00B<Z:github.com/mihirk-khode/motocabz-common/genproto/auth;authb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_auth_auth_proto_goTypes = []any{
	(*Enum)(nil),                // 0: auth.Enum
	(*EnumResponse)(nil),        // 1: auth.EnumResponse
	(*EnumRequest)(nil),         // 2: auth.EnumRequest
	(*SendOtpRequest)(nil),      // 3: auth.SendOtpRequest
	(*SendOtpResponse)(nil),     // 4: auth.SendOtpResponse
	(*VerifyOtpRequest)(nil),    // 5: auth.VerifyOtpRequest
	(*VerifyOtpResponse)(nil),   // 6: auth.VerifyOtpResponse
	(*GoogleAuthRequest)(nil),   // 7: auth.GoogleAuthRequest
	(*GoogleAuthResponse)(nil),  // 8: auth.GoogleAuthResponse
	(*RefreshTokenRequest)(nil), // 9: auth.RefreshTokenRequest
	(*TokenResponse)(nil),       // 10: auth.TokenResponse
	(*ParseTokenRequest)(nil),   // 11: auth.ParseTokenRequest
	(*ParseTokenResponse)(nil),  // 12: auth.ParseTokenResponse
	(*UserAuthRequest)(nil),     // 13: auth.UserAuthRequest
	(*UserAuthResponse)(nil),    // 14: auth.UserAuthResponse
}
var file_auth_auth_proto_depIdxs = []int32{
	0,  // 0: auth.EnumResponse.enum:type_name -> auth.Enum
	2,  // 1: auth.SendOtpRequest.role:type_name -> auth.EnumRequest
	2,  // 2: auth.VerifyOtpRequest.role:type_name -> auth.EnumRequest
	2,  // 3: auth.GoogleAuthRequest.role:type_name -> auth.EnumRequest
	1,  // 4: auth.ParseTokenResponse.role:type_name -> auth.EnumResponse
	2,  // 5: auth.UserAuthRequest.role:type_name -> auth.EnumRequest
	10, // 6: auth.UserAuthResponse.token:type_name -> auth.TokenResponse
	3,  // 7: auth.AuthService.SendOTP:input_type -> auth.SendOtpRequest
	5,  // 8: auth.AuthService.VerifyOTP:input_type -> auth.VerifyOtpRequest
	7,  // 9: auth.AuthService.GoogleSignup:input_type -> auth.GoogleAuthRequest
	7,  // 10: auth.AuthService.GoogleLogin:input_type -> auth.GoogleAuthRequest
	9,  // 11: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	11, // 12: auth.AuthService.ParseToken:input_type -> auth.ParseTokenRequest
	13, // 13: auth.AuthService.UserAuth:input_type -> auth.UserAuthRequest
	4,  // 14: auth.AuthService.SendOTP:output_type -> auth.SendOtpResponse
	6,  // 15: auth.AuthService.VerifyOTP:output_type -> auth.VerifyOtpResponse
	8,  // 16: auth.AuthService.GoogleSignup:output_type -> auth.GoogleAuthResponse
	8,  // 17: auth.AuthService.GoogleLogin:output_type -> auth.GoogleAuthResponse
	10, // 18: auth.AuthService.RefreshToken:output_type -> auth.TokenResponse
	12, // 19: auth.AuthService.ParseToken:output_type -> auth.ParseTokenResponse
	14, // 20: auth.AuthService.UserAuth:output_type -> auth.UserAuthResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
