// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: trip/trip.proto

package trip

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TripService_CreateTrip_FullMethodName                 = "/trip.TripService/CreateTrip"
	TripService_SubmitBidOrOffer_FullMethodName           = "/trip.TripService/SubmitBidOrOffer"
	TripService_AcceptOffer_FullMethodName                = "/trip.TripService/AcceptOffer"
	TripService_InstantAccept_FullMethodName              = "/trip.TripService/InstantAccept"
	TripService_GetTrip_FullMethodName                    = "/trip.TripService/GetTrip"
	TripService_GetActiveTrips_FullMethodName             = "/trip.TripService/GetActiveTrips"
	TripService_GetActiveTripsByRider_FullMethodName      = "/trip.TripService/GetActiveTripsByRider"
	TripService_AcceptTrip_FullMethodName                 = "/trip.TripService/AcceptTrip"
	TripService_CancelTrip_FullMethodName                 = "/trip.TripService/CancelTrip"
	TripService_CompleteTrip_FullMethodName               = "/trip.TripService/CompleteTrip"
	TripService_GetBiddingSession_FullMethodName          = "/trip.TripService/GetBiddingSession"
	TripService_GetBiddingSessionsByRider_FullMethodName  = "/trip.TripService/GetBiddingSessionsByRider"
	TripService_GetBiddingSessionsByDriver_FullMethodName = "/trip.TripService/GetBiddingSessionsByDriver"
	TripService_InstantMatch_FullMethodName               = "/trip.TripService/InstantMatch"
	TripService_GetInstantMatchStatus_FullMethodName      = "/trip.TripService/GetInstantMatchStatus"
	TripService_CancelInstantMatch_FullMethodName         = "/trip.TripService/CancelInstantMatch"
	TripService_GetTripHistoryByRider_FullMethodName      = "/trip.TripService/GetTripHistoryByRider"
	TripService_GetTripHistoryByDriver_FullMethodName     = "/trip.TripService/GetTripHistoryByDriver"
)

// TripServiceClient is the client API for TripService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripServiceClient interface {
	CreateTrip(ctx context.Context, in *RqTrip, opts ...grpc.CallOption) (*RsTrip, error)
	SubmitBidOrOffer(ctx context.Context, in *RqBidOrOffer, opts ...grpc.CallOption) (*RsBidOrOffer, error)
	AcceptOffer(ctx context.Context, in *RqAcceptOffer, opts ...grpc.CallOption) (*RsAcceptOffer, error)
	InstantAccept(ctx context.Context, in *RqInstantAccept, opts ...grpc.CallOption) (*RsInstantAccept, error)
	GetTrip(ctx context.Context, in *RqGetTrip, opts ...grpc.CallOption) (*RsTrip, error)
	GetActiveTrips(ctx context.Context, in *RqGetActiveTrips, opts ...grpc.CallOption) (*RsGetActiveTrips, error)
	GetActiveTripsByRider(ctx context.Context, in *RqGetActiveTripsByRider, opts ...grpc.CallOption) (*RsGetActiveTrips, error)
	AcceptTrip(ctx context.Context, in *RqAcceptTrip, opts ...grpc.CallOption) (*RsAcceptTrip, error)
	CancelTrip(ctx context.Context, in *RqCancelTrip, opts ...grpc.CallOption) (*RsCancelTrip, error)
	CompleteTrip(ctx context.Context, in *RqCompleteTrip, opts ...grpc.CallOption) (*RsCompleteTrip, error)
	GetBiddingSession(ctx context.Context, in *RqGetBiddingSession, opts ...grpc.CallOption) (*RsGetBiddingSession, error)
	GetBiddingSessionsByRider(ctx context.Context, in *RqGetBiddingSessionsByRider, opts ...grpc.CallOption) (*RsGetBiddingSessionsByRider, error)
	GetBiddingSessionsByDriver(ctx context.Context, in *RqGetBiddingSessionsByDriver, opts ...grpc.CallOption) (*RsGetBiddingSessionsByDriver, error)
	InstantMatch(ctx context.Context, in *RqInstantMatch, opts ...grpc.CallOption) (*RsInstantMatch, error)
	GetInstantMatchStatus(ctx context.Context, in *RqGetInstantMatchStatus, opts ...grpc.CallOption) (*RsGetInstantMatchStatus, error)
	CancelInstantMatch(ctx context.Context, in *RqCancelInstantMatch, opts ...grpc.CallOption) (*RsCancelInstantMatch, error)
	GetTripHistoryByRider(ctx context.Context, in *RqGetTripHistoryByRider, opts ...grpc.CallOption) (*RsGetTripHistory, error)
	GetTripHistoryByDriver(ctx context.Context, in *RqGetTripHistoryByDriver, opts ...grpc.CallOption) (*RsGetTripHistory, error)
}

type tripServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServiceClient(cc grpc.ClientConnInterface) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) CreateTrip(ctx context.Context, in *RqTrip, opts ...grpc.CallOption) (*RsTrip, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsTrip)
	err := c.cc.Invoke(ctx, TripService_CreateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) SubmitBidOrOffer(ctx context.Context, in *RqBidOrOffer, opts ...grpc.CallOption) (*RsBidOrOffer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsBidOrOffer)
	err := c.cc.Invoke(ctx, TripService_SubmitBidOrOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AcceptOffer(ctx context.Context, in *RqAcceptOffer, opts ...grpc.CallOption) (*RsAcceptOffer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsAcceptOffer)
	err := c.cc.Invoke(ctx, TripService_AcceptOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) InstantAccept(ctx context.Context, in *RqInstantAccept, opts ...grpc.CallOption) (*RsInstantAccept, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsInstantAccept)
	err := c.cc.Invoke(ctx, TripService_InstantAccept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTrip(ctx context.Context, in *RqGetTrip, opts ...grpc.CallOption) (*RsTrip, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsTrip)
	err := c.cc.Invoke(ctx, TripService_GetTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetActiveTrips(ctx context.Context, in *RqGetActiveTrips, opts ...grpc.CallOption) (*RsGetActiveTrips, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetActiveTrips)
	err := c.cc.Invoke(ctx, TripService_GetActiveTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetActiveTripsByRider(ctx context.Context, in *RqGetActiveTripsByRider, opts ...grpc.CallOption) (*RsGetActiveTrips, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetActiveTrips)
	err := c.cc.Invoke(ctx, TripService_GetActiveTripsByRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AcceptTrip(ctx context.Context, in *RqAcceptTrip, opts ...grpc.CallOption) (*RsAcceptTrip, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsAcceptTrip)
	err := c.cc.Invoke(ctx, TripService_AcceptTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CancelTrip(ctx context.Context, in *RqCancelTrip, opts ...grpc.CallOption) (*RsCancelTrip, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsCancelTrip)
	err := c.cc.Invoke(ctx, TripService_CancelTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CompleteTrip(ctx context.Context, in *RqCompleteTrip, opts ...grpc.CallOption) (*RsCompleteTrip, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsCompleteTrip)
	err := c.cc.Invoke(ctx, TripService_CompleteTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetBiddingSession(ctx context.Context, in *RqGetBiddingSession, opts ...grpc.CallOption) (*RsGetBiddingSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetBiddingSession)
	err := c.cc.Invoke(ctx, TripService_GetBiddingSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetBiddingSessionsByRider(ctx context.Context, in *RqGetBiddingSessionsByRider, opts ...grpc.CallOption) (*RsGetBiddingSessionsByRider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetBiddingSessionsByRider)
	err := c.cc.Invoke(ctx, TripService_GetBiddingSessionsByRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetBiddingSessionsByDriver(ctx context.Context, in *RqGetBiddingSessionsByDriver, opts ...grpc.CallOption) (*RsGetBiddingSessionsByDriver, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetBiddingSessionsByDriver)
	err := c.cc.Invoke(ctx, TripService_GetBiddingSessionsByDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) InstantMatch(ctx context.Context, in *RqInstantMatch, opts ...grpc.CallOption) (*RsInstantMatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsInstantMatch)
	err := c.cc.Invoke(ctx, TripService_InstantMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetInstantMatchStatus(ctx context.Context, in *RqGetInstantMatchStatus, opts ...grpc.CallOption) (*RsGetInstantMatchStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetInstantMatchStatus)
	err := c.cc.Invoke(ctx, TripService_GetInstantMatchStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CancelInstantMatch(ctx context.Context, in *RqCancelInstantMatch, opts ...grpc.CallOption) (*RsCancelInstantMatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsCancelInstantMatch)
	err := c.cc.Invoke(ctx, TripService_CancelInstantMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTripHistoryByRider(ctx context.Context, in *RqGetTripHistoryByRider, opts ...grpc.CallOption) (*RsGetTripHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetTripHistory)
	err := c.cc.Invoke(ctx, TripService_GetTripHistoryByRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTripHistoryByDriver(ctx context.Context, in *RqGetTripHistoryByDriver, opts ...grpc.CallOption) (*RsGetTripHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetTripHistory)
	err := c.cc.Invoke(ctx, TripService_GetTripHistoryByDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripServiceServer is the server API for TripService service.
// All implementations must embed UnimplementedTripServiceServer
// for forward compatibility.
type TripServiceServer interface {
	CreateTrip(context.Context, *RqTrip) (*RsTrip, error)
	SubmitBidOrOffer(context.Context, *RqBidOrOffer) (*RsBidOrOffer, error)
	AcceptOffer(context.Context, *RqAcceptOffer) (*RsAcceptOffer, error)
	InstantAccept(context.Context, *RqInstantAccept) (*RsInstantAccept, error)
	GetTrip(context.Context, *RqGetTrip) (*RsTrip, error)
	GetActiveTrips(context.Context, *RqGetActiveTrips) (*RsGetActiveTrips, error)
	GetActiveTripsByRider(context.Context, *RqGetActiveTripsByRider) (*RsGetActiveTrips, error)
	AcceptTrip(context.Context, *RqAcceptTrip) (*RsAcceptTrip, error)
	CancelTrip(context.Context, *RqCancelTrip) (*RsCancelTrip, error)
	CompleteTrip(context.Context, *RqCompleteTrip) (*RsCompleteTrip, error)
	GetBiddingSession(context.Context, *RqGetBiddingSession) (*RsGetBiddingSession, error)
	GetBiddingSessionsByRider(context.Context, *RqGetBiddingSessionsByRider) (*RsGetBiddingSessionsByRider, error)
	GetBiddingSessionsByDriver(context.Context, *RqGetBiddingSessionsByDriver) (*RsGetBiddingSessionsByDriver, error)
	InstantMatch(context.Context, *RqInstantMatch) (*RsInstantMatch, error)
	GetInstantMatchStatus(context.Context, *RqGetInstantMatchStatus) (*RsGetInstantMatchStatus, error)
	CancelInstantMatch(context.Context, *RqCancelInstantMatch) (*RsCancelInstantMatch, error)
	GetTripHistoryByRider(context.Context, *RqGetTripHistoryByRider) (*RsGetTripHistory, error)
	GetTripHistoryByDriver(context.Context, *RqGetTripHistoryByDriver) (*RsGetTripHistory, error)
	mustEmbedUnimplementedTripServiceServer()
}

// UnimplementedTripServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTripServiceServer struct{}

func (UnimplementedTripServiceServer) CreateTrip(context.Context, *RqTrip) (*RsTrip, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrip not implemented")
}
func (UnimplementedTripServiceServer) SubmitBidOrOffer(context.Context, *RqBidOrOffer) (*RsBidOrOffer, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBidOrOffer not implemented")
}
func (UnimplementedTripServiceServer) AcceptOffer(context.Context, *RqAcceptOffer) (*RsAcceptOffer, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptOffer not implemented")
}
func (UnimplementedTripServiceServer) InstantAccept(context.Context, *RqInstantAccept) (*RsInstantAccept, error) {
	return nil, status.Error(codes.Unimplemented, "method InstantAccept not implemented")
}
func (UnimplementedTripServiceServer) GetTrip(context.Context, *RqGetTrip) (*RsTrip, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrip not implemented")
}
func (UnimplementedTripServiceServer) GetActiveTrips(context.Context, *RqGetActiveTrips) (*RsGetActiveTrips, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveTrips not implemented")
}
func (UnimplementedTripServiceServer) GetActiveTripsByRider(context.Context, *RqGetActiveTripsByRider) (*RsGetActiveTrips, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveTripsByRider not implemented")
}
func (UnimplementedTripServiceServer) AcceptTrip(context.Context, *RqAcceptTrip) (*RsAcceptTrip, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptTrip not implemented")
}
func (UnimplementedTripServiceServer) CancelTrip(context.Context, *RqCancelTrip) (*RsCancelTrip, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTrip not implemented")
}
func (UnimplementedTripServiceServer) CompleteTrip(context.Context, *RqCompleteTrip) (*RsCompleteTrip, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTrip not implemented")
}
func (UnimplementedTripServiceServer) GetBiddingSession(context.Context, *RqGetBiddingSession) (*RsGetBiddingSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBiddingSession not implemented")
}
func (UnimplementedTripServiceServer) GetBiddingSessionsByRider(context.Context, *RqGetBiddingSessionsByRider) (*RsGetBiddingSessionsByRider, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBiddingSessionsByRider not implemented")
}
func (UnimplementedTripServiceServer) GetBiddingSessionsByDriver(context.Context, *RqGetBiddingSessionsByDriver) (*RsGetBiddingSessionsByDriver, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBiddingSessionsByDriver not implemented")
}
func (UnimplementedTripServiceServer) InstantMatch(context.Context, *RqInstantMatch) (*RsInstantMatch, error) {
	return nil, status.Error(codes.Unimplemented, "method InstantMatch not implemented")
}
func (UnimplementedTripServiceServer) GetInstantMatchStatus(context.Context, *RqGetInstantMatchStatus) (*RsGetInstantMatchStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstantMatchStatus not implemented")
}
func (UnimplementedTripServiceServer) CancelInstantMatch(context.Context, *RqCancelInstantMatch) (*RsCancelInstantMatch, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInstantMatch not implemented")
}
func (UnimplementedTripServiceServer) GetTripHistoryByRider(context.Context, *RqGetTripHistoryByRider) (*RsGetTripHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTripHistoryByRider not implemented")
}
func (UnimplementedTripServiceServer) GetTripHistoryByDriver(context.Context, *RqGetTripHistoryByDriver) (*RsGetTripHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTripHistoryByDriver not implemented")
}
func (UnimplementedTripServiceServer) mustEmbedUnimplementedTripServiceServer() {}
func (UnimplementedTripServiceServer) testEmbeddedByValue()                     {}

// UnsafeTripServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripServiceServer will
// result in compilation errors.
type UnsafeTripServiceServer interface {
	mustEmbedUnimplementedTripServiceServer()
}

func RegisterTripServiceServer(s grpc.ServiceRegistrar, srv TripServiceServer) {
	// If the following call panics, it indicates UnimplementedTripServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TripService_ServiceDesc, srv)
}

func _TripService_CreateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqTrip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CreateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CreateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CreateTrip(ctx, req.(*RqTrip))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_SubmitBidOrOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqBidOrOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).SubmitBidOrOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_SubmitBidOrOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).SubmitBidOrOffer(ctx, req.(*RqBidOrOffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AcceptOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqAcceptOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AcceptOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AcceptOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AcceptOffer(ctx, req.(*RqAcceptOffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_InstantAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqInstantAccept)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).InstantAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_InstantAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).InstantAccept(ctx, req.(*RqInstantAccept))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetTrip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTrip(ctx, req.(*RqGetTrip))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetActiveTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetActiveTrips)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetActiveTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetActiveTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetActiveTrips(ctx, req.(*RqGetActiveTrips))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetActiveTripsByRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetActiveTripsByRider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetActiveTripsByRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetActiveTripsByRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetActiveTripsByRider(ctx, req.(*RqGetActiveTripsByRider))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AcceptTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqAcceptTrip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AcceptTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AcceptTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AcceptTrip(ctx, req.(*RqAcceptTrip))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CancelTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqCancelTrip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CancelTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CancelTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CancelTrip(ctx, req.(*RqCancelTrip))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CompleteTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqCompleteTrip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CompleteTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CompleteTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CompleteTrip(ctx, req.(*RqCompleteTrip))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetBiddingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetBiddingSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetBiddingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetBiddingSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetBiddingSession(ctx, req.(*RqGetBiddingSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetBiddingSessionsByRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetBiddingSessionsByRider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetBiddingSessionsByRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetBiddingSessionsByRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetBiddingSessionsByRider(ctx, req.(*RqGetBiddingSessionsByRider))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetBiddingSessionsByDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetBiddingSessionsByDriver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetBiddingSessionsByDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetBiddingSessionsByDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetBiddingSessionsByDriver(ctx, req.(*RqGetBiddingSessionsByDriver))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_InstantMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqInstantMatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).InstantMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_InstantMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).InstantMatch(ctx, req.(*RqInstantMatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetInstantMatchStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetInstantMatchStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetInstantMatchStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetInstantMatchStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetInstantMatchStatus(ctx, req.(*RqGetInstantMatchStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CancelInstantMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqCancelInstantMatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CancelInstantMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CancelInstantMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CancelInstantMatch(ctx, req.(*RqCancelInstantMatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTripHistoryByRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetTripHistoryByRider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTripHistoryByRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTripHistoryByRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTripHistoryByRider(ctx, req.(*RqGetTripHistoryByRider))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTripHistoryByDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetTripHistoryByDriver)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTripHistoryByDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTripHistoryByDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTripHistoryByDriver(ctx, req.(*RqGetTripHistoryByDriver))
	}
	return interceptor(ctx, in, info, handler)
}

// TripService_ServiceDesc is the grpc.ServiceDesc for TripService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrip",
			Handler:    _TripService_CreateTrip_Handler,
		},
		{
			MethodName: "SubmitBidOrOffer",
			Handler:    _TripService_SubmitBidOrOffer_Handler,
		},
		{
			MethodName: "AcceptOffer",
			Handler:    _TripService_AcceptOffer_Handler,
		},
		{
			MethodName: "InstantAccept",
			Handler:    _TripService_InstantAccept_Handler,
		},
		{
			MethodName: "GetTrip",
			Handler:    _TripService_GetTrip_Handler,
		},
		{
			MethodName: "GetActiveTrips",
			Handler:    _TripService_GetActiveTrips_Handler,
		},
		{
			MethodName: "GetActiveTripsByRider",
			Handler:    _TripService_GetActiveTripsByRider_Handler,
		},
		{
			MethodName: "AcceptTrip",
			Handler:    _TripService_AcceptTrip_Handler,
		},
		{
			MethodName: "CancelTrip",
			Handler:    _TripService_CancelTrip_Handler,
		},
		{
			MethodName: "CompleteTrip",
			Handler:    _TripService_CompleteTrip_Handler,
		},
		{
			MethodName: "GetBiddingSession",
			Handler:    _TripService_GetBiddingSession_Handler,
		},
		{
			MethodName: "GetBiddingSessionsByRider",
			Handler:    _TripService_GetBiddingSessionsByRider_Handler,
		},
		{
			MethodName: "GetBiddingSessionsByDriver",
			Handler:    _TripService_GetBiddingSessionsByDriver_Handler,
		},
		{
			MethodName: "InstantMatch",
			Handler:    _TripService_InstantMatch_Handler,
		},
		{
			MethodName: "GetInstantMatchStatus",
			Handler:    _TripService_GetInstantMatchStatus_Handler,
		},
		{
			MethodName: "CancelInstantMatch",
			Handler:    _TripService_CancelInstantMatch_Handler,
		},
		{
			MethodName: "GetTripHistoryByRider",
			Handler:    _TripService_GetTripHistoryByRider_Handler,
		},
		{
			MethodName: "GetTripHistoryByDriver",
			Handler:    _TripService_GetTripHistoryByDriver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip/trip.proto",
}

const (
	NegotiationService_CreateNegotiationSession_FullMethodName = "/trip.NegotiationService/CreateNegotiationSession"
	NegotiationService_SubmitOffer_FullMethodName              = "/trip.NegotiationService/SubmitOffer"
	NegotiationService_RespondToOffer_FullMethodName           = "/trip.NegotiationService/RespondToOffer"
	NegotiationService_DriverRespondToCounter_FullMethodName   = "/trip.NegotiationService/DriverRespondToCounter"
	NegotiationService_GetNegotiationSession_FullMethodName    = "/trip.NegotiationService/GetNegotiationSession"
	NegotiationService_CancelNegotiation_FullMethodName        = "/trip.NegotiationService/CancelNegotiation"
)

// NegotiationServiceClient is the client API for NegotiationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NegotiationServiceClient interface {
	CreateNegotiationSession(ctx context.Context, in *RqCreateNegotiationSession, opts ...grpc.CallOption) (*RsCreateNegotiationSession, error)
	SubmitOffer(ctx context.Context, in *RqSubmitOffer, opts ...grpc.CallOption) (*RsSubmitOffer, error)
	RespondToOffer(ctx context.Context, in *RqRespondToOffer, opts ...grpc.CallOption) (*RsRespondToOffer, error)
	DriverRespondToCounter(ctx context.Context, in *RqDriverRespondToCounter, opts ...grpc.CallOption) (*RsDriverRespondToCounter, error)
	GetNegotiationSession(ctx context.Context, in *RqGetNegotiationSession, opts ...grpc.CallOption) (*RsGetNegotiationSession, error)
	CancelNegotiation(ctx context.Context, in *RqCancelNegotiation, opts ...grpc.CallOption) (*RsCancelNegotiation, error)
}

type negotiationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNegotiationServiceClient(cc grpc.ClientConnInterface) NegotiationServiceClient {
	return &negotiationServiceClient{cc}
}

func (c *negotiationServiceClient) CreateNegotiationSession(ctx context.Context, in *RqCreateNegotiationSession, opts ...grpc.CallOption) (*RsCreateNegotiationSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsCreateNegotiationSession)
	err := c.cc.Invoke(ctx, NegotiationService_CreateNegotiationSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *negotiationServiceClient) SubmitOffer(ctx context.Context, in *RqSubmitOffer, opts ...grpc.CallOption) (*RsSubmitOffer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsSubmitOffer)
	err := c.cc.Invoke(ctx, NegotiationService_SubmitOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *negotiationServiceClient) RespondToOffer(ctx context.Context, in *RqRespondToOffer, opts ...grpc.CallOption) (*RsRespondToOffer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsRespondToOffer)
	err := c.cc.Invoke(ctx, NegotiationService_RespondToOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *negotiationServiceClient) DriverRespondToCounter(ctx context.Context, in *RqDriverRespondToCounter, opts ...grpc.CallOption) (*RsDriverRespondToCounter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsDriverRespondToCounter)
	err := c.cc.Invoke(ctx, NegotiationService_DriverRespondToCounter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *negotiationServiceClient) GetNegotiationSession(ctx context.Context, in *RqGetNegotiationSession, opts ...grpc.CallOption) (*RsGetNegotiationSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsGetNegotiationSession)
	err := c.cc.Invoke(ctx, NegotiationService_GetNegotiationSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *negotiationServiceClient) CancelNegotiation(ctx context.Context, in *RqCancelNegotiation, opts ...grpc.CallOption) (*RsCancelNegotiation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RsCancelNegotiation)
	err := c.cc.Invoke(ctx, NegotiationService_CancelNegotiation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NegotiationServiceServer is the server API for NegotiationService service.
// All implementations must embed UnimplementedNegotiationServiceServer
// for forward compatibility.
type NegotiationServiceServer interface {
	CreateNegotiationSession(context.Context, *RqCreateNegotiationSession) (*RsCreateNegotiationSession, error)
	SubmitOffer(context.Context, *RqSubmitOffer) (*RsSubmitOffer, error)
	RespondToOffer(context.Context, *RqRespondToOffer) (*RsRespondToOffer, error)
	DriverRespondToCounter(context.Context, *RqDriverRespondToCounter) (*RsDriverRespondToCounter, error)
	GetNegotiationSession(context.Context, *RqGetNegotiationSession) (*RsGetNegotiationSession, error)
	CancelNegotiation(context.Context, *RqCancelNegotiation) (*RsCancelNegotiation, error)
	mustEmbedUnimplementedNegotiationServiceServer()
}

// UnimplementedNegotiationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNegotiationServiceServer struct{}

func (UnimplementedNegotiationServiceServer) CreateNegotiationSession(context.Context, *RqCreateNegotiationSession) (*RsCreateNegotiationSession, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNegotiationSession not implemented")
}
func (UnimplementedNegotiationServiceServer) SubmitOffer(context.Context, *RqSubmitOffer) (*RsSubmitOffer, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitOffer not implemented")
}
func (UnimplementedNegotiationServiceServer) RespondToOffer(context.Context, *RqRespondToOffer) (*RsRespondToOffer, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToOffer not implemented")
}
func (UnimplementedNegotiationServiceServer) DriverRespondToCounter(context.Context, *RqDriverRespondToCounter) (*RsDriverRespondToCounter, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverRespondToCounter not implemented")
}
func (UnimplementedNegotiationServiceServer) GetNegotiationSession(context.Context, *RqGetNegotiationSession) (*RsGetNegotiationSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNegotiationSession not implemented")
}
func (UnimplementedNegotiationServiceServer) CancelNegotiation(context.Context, *RqCancelNegotiation) (*RsCancelNegotiation, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelNegotiation not implemented")
}
func (UnimplementedNegotiationServiceServer) mustEmbedUnimplementedNegotiationServiceServer() {}
func (UnimplementedNegotiationServiceServer) testEmbeddedByValue()                            {}

// UnsafeNegotiationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NegotiationServiceServer will
// result in compilation errors.
type UnsafeNegotiationServiceServer interface {
	mustEmbedUnimplementedNegotiationServiceServer()
}

func RegisterNegotiationServiceServer(s grpc.ServiceRegistrar, srv NegotiationServiceServer) {
	// If the following call panics, it indicates UnimplementedNegotiationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NegotiationService_ServiceDesc, srv)
}

func _NegotiationService_CreateNegotiationSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqCreateNegotiationSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegotiationServiceServer).CreateNegotiationSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NegotiationService_CreateNegotiationSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegotiationServiceServer).CreateNegotiationSession(ctx, req.(*RqCreateNegotiationSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _NegotiationService_SubmitOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqSubmitOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegotiationServiceServer).SubmitOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NegotiationService_SubmitOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegotiationServiceServer).SubmitOffer(ctx, req.(*RqSubmitOffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _NegotiationService_RespondToOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqRespondToOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegotiationServiceServer).RespondToOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NegotiationService_RespondToOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegotiationServiceServer).RespondToOffer(ctx, req.(*RqRespondToOffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _NegotiationService_DriverRespondToCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqDriverRespondToCounter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegotiationServiceServer).DriverRespondToCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NegotiationService_DriverRespondToCounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegotiationServiceServer).DriverRespondToCounter(ctx, req.(*RqDriverRespondToCounter))
	}
	return interceptor(ctx, in, info, handler)
}

func _NegotiationService_GetNegotiationSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqGetNegotiationSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegotiationServiceServer).GetNegotiationSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NegotiationService_GetNegotiationSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegotiationServiceServer).GetNegotiationSession(ctx, req.(*RqGetNegotiationSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _NegotiationService_CancelNegotiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RqCancelNegotiation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegotiationServiceServer).CancelNegotiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NegotiationService_CancelNegotiation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegotiationServiceServer).CancelNegotiation(ctx, req.(*RqCancelNegotiation))
	}
	return interceptor(ctx, in, info, handler)
}

// NegotiationService_ServiceDesc is the grpc.ServiceDesc for NegotiationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NegotiationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.NegotiationService",
	HandlerType: (*NegotiationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNegotiationSession",
			Handler:    _NegotiationService_CreateNegotiationSession_Handler,
		},
		{
			MethodName: "SubmitOffer",
			Handler:    _NegotiationService_SubmitOffer_Handler,
		},
		{
			MethodName: "RespondToOffer",
			Handler:    _NegotiationService_RespondToOffer_Handler,
		},
		{
			MethodName: "DriverRespondToCounter",
			Handler:    _NegotiationService_DriverRespondToCounter_Handler,
		},
		{
			MethodName: "GetNegotiationSession",
			Handler:    _NegotiationService_GetNegotiationSession_Handler,
		},
		{
			MethodName: "CancelNegotiation",
			Handler:    _NegotiationService_CancelNegotiation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip/trip.proto",
}
