// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.1
// source: rider.proto

package rider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum value representation
type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_rider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{0}
}

func (x *Enum) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Enum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enum) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Enum) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Enum response
type RsEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enum          []*Enum                `protobuf:"bytes,1,rep,name=enum,proto3" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RsEnum) Reset() {
	*x = RsEnum{}
	mi := &file_rider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsEnum) ProtoMessage() {}

func (x *RsEnum) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsEnum.ProtoReflect.Descriptor instead.
func (*RsEnum) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{1}
}

func (x *RsEnum) GetEnum() []*Enum {
	if x != nil {
		return x.Enum
	}
	return nil
}

type RqEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnumType      string                 `protobuf:"bytes,1,opt,name=enum_type,json=enumType,proto3" json:"enum_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RqEnum) Reset() {
	*x = RqEnum{}
	mi := &file_rider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RqEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqEnum) ProtoMessage() {}

func (x *RqEnum) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqEnum.ProtoReflect.Descriptor instead.
func (*RqEnum) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{2}
}

func (x *RqEnum) GetEnumType() string {
	if x != nil {
		return x.EnumType
	}
	return ""
}

// Rider info request
type RqGetRiderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RqGetRiderInfo) Reset() {
	*x = RqGetRiderInfo{}
	mi := &file_rider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RqGetRiderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqGetRiderInfo) ProtoMessage() {}

func (x *RqGetRiderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqGetRiderInfo.ProtoReflect.Descriptor instead.
func (*RqGetRiderInfo) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{3}
}

func (x *RqGetRiderInfo) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

// Rider info response
type RsGetRiderInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RiderId              string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Rating               float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	PreferredVehicleType *RsEnum                `protobuf:"bytes,6,opt,name=preferred_vehicle_type,json=preferredVehicleType,proto3" json:"preferred_vehicle_type,omitempty"`
	InstantMatchEnabled  bool                   `protobuf:"varint,7,opt,name=instant_match_enabled,json=instantMatchEnabled,proto3" json:"instant_match_enabled,omitempty"`
	PaymentMethod        *RsEnum                `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RsGetRiderInfo) Reset() {
	*x = RsGetRiderInfo{}
	mi := &file_rider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsGetRiderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsGetRiderInfo) ProtoMessage() {}

func (x *RsGetRiderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsGetRiderInfo.ProtoReflect.Descriptor instead.
func (*RsGetRiderInfo) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{4}
}

func (x *RsGetRiderInfo) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RsGetRiderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RsGetRiderInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RsGetRiderInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RsGetRiderInfo) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RsGetRiderInfo) GetPreferredVehicleType() *RsEnum {
	if x != nil {
		return x.PreferredVehicleType
	}
	return nil
}

func (x *RsGetRiderInfo) GetInstantMatchEnabled() bool {
	if x != nil {
		return x.InstantMatchEnabled
	}
	return false
}

func (x *RsGetRiderInfo) GetPaymentMethod() *RsEnum {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

// Trip history request
type RqGetTripHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RqGetTripHistory) Reset() {
	*x = RqGetTripHistory{}
	mi := &file_rider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RqGetTripHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqGetTripHistory) ProtoMessage() {}

func (x *RqGetTripHistory) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqGetTripHistory.ProtoReflect.Descriptor instead.
func (*RqGetTripHistory) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{5}
}

func (x *RqGetTripHistory) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RqGetTripHistory) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RqGetTripHistory) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Trip history response
type RsGetTripHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trips         []*TripSummary         `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RsGetTripHistory) Reset() {
	*x = RsGetTripHistory{}
	mi := &file_rider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsGetTripHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsGetTripHistory) ProtoMessage() {}

func (x *RsGetTripHistory) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsGetTripHistory.ProtoReflect.Descriptor instead.
func (*RsGetTripHistory) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{6}
}

func (x *RsGetTripHistory) GetTrips() []*TripSummary {
	if x != nil {
		return x.Trips
	}
	return nil
}

func (x *RsGetTripHistory) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Trip summary
type TripSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TripId         string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	DriverId       string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DriverName     string                 `protobuf:"bytes,3,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	VehicleType    *RsEnum                `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	StartLatitude  float64                `protobuf:"fixed64,5,opt,name=start_latitude,json=startLatitude,proto3" json:"start_latitude,omitempty"`
	StartLongitude float64                `protobuf:"fixed64,6,opt,name=start_longitude,json=startLongitude,proto3" json:"start_longitude,omitempty"`
	EndLatitude    float64                `protobuf:"fixed64,7,opt,name=end_latitude,json=endLatitude,proto3" json:"end_latitude,omitempty"`
	EndLongitude   float64                `protobuf:"fixed64,8,opt,name=end_longitude,json=endLongitude,proto3" json:"end_longitude,omitempty"`
	Price          float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	Status         *RsEnum                `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt    string                 `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TripSummary) Reset() {
	*x = TripSummary{}
	mi := &file_rider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripSummary) ProtoMessage() {}

func (x *TripSummary) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripSummary.ProtoReflect.Descriptor instead.
func (*TripSummary) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{7}
}

func (x *TripSummary) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripSummary) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *TripSummary) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *TripSummary) GetVehicleType() *RsEnum {
	if x != nil {
		return x.VehicleType
	}
	return nil
}

func (x *TripSummary) GetStartLatitude() float64 {
	if x != nil {
		return x.StartLatitude
	}
	return 0
}

func (x *TripSummary) GetStartLongitude() float64 {
	if x != nil {
		return x.StartLongitude
	}
	return 0
}

func (x *TripSummary) GetEndLatitude() float64 {
	if x != nil {
		return x.EndLatitude
	}
	return 0
}

func (x *TripSummary) GetEndLongitude() float64 {
	if x != nil {
		return x.EndLongitude
	}
	return 0
}

func (x *TripSummary) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TripSummary) GetStatus() *RsEnum {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TripSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TripSummary) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

// Rider preferences request
type RqGetRiderPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RqGetRiderPreferences) Reset() {
	*x = RqGetRiderPreferences{}
	mi := &file_rider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RqGetRiderPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqGetRiderPreferences) ProtoMessage() {}

func (x *RqGetRiderPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqGetRiderPreferences.ProtoReflect.Descriptor instead.
func (*RqGetRiderPreferences) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{8}
}

func (x *RqGetRiderPreferences) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

// Rider preferences response
type RsGetRiderPreferences struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RiderId              string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	PreferredVehicleType *RsEnum                `protobuf:"bytes,2,opt,name=preferred_vehicle_type,json=preferredVehicleType,proto3" json:"preferred_vehicle_type,omitempty"`
	InstantMatchEnabled  bool                   `protobuf:"varint,3,opt,name=instant_match_enabled,json=instantMatchEnabled,proto3" json:"instant_match_enabled,omitempty"`
	PaymentMethod        *RsEnum                `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,5,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	Language             *RsEnum                `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RsGetRiderPreferences) Reset() {
	*x = RsGetRiderPreferences{}
	mi := &file_rider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsGetRiderPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsGetRiderPreferences) ProtoMessage() {}

func (x *RsGetRiderPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsGetRiderPreferences.ProtoReflect.Descriptor instead.
func (*RsGetRiderPreferences) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{9}
}

func (x *RsGetRiderPreferences) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RsGetRiderPreferences) GetPreferredVehicleType() *RsEnum {
	if x != nil {
		return x.PreferredVehicleType
	}
	return nil
}

func (x *RsGetRiderPreferences) GetInstantMatchEnabled() bool {
	if x != nil {
		return x.InstantMatchEnabled
	}
	return false
}

func (x *RsGetRiderPreferences) GetPaymentMethod() *RsEnum {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *RsGetRiderPreferences) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *RsGetRiderPreferences) GetLanguage() *RsEnum {
	if x != nil {
		return x.Language
	}
	return nil
}

// Update rider preferences request
type RqUpdateRiderPreferences struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RiderId              string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	PreferredVehicleType *RqEnum                `protobuf:"bytes,2,opt,name=preferred_vehicle_type,json=preferredVehicleType,proto3" json:"preferred_vehicle_type,omitempty"`
	InstantMatchEnabled  bool                   `protobuf:"varint,3,opt,name=instant_match_enabled,json=instantMatchEnabled,proto3" json:"instant_match_enabled,omitempty"`
	PaymentMethod        *RqEnum                `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	NotificationsEnabled bool                   `protobuf:"varint,5,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	Language             *RqEnum                `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RqUpdateRiderPreferences) Reset() {
	*x = RqUpdateRiderPreferences{}
	mi := &file_rider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RqUpdateRiderPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqUpdateRiderPreferences) ProtoMessage() {}

func (x *RqUpdateRiderPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqUpdateRiderPreferences.ProtoReflect.Descriptor instead.
func (*RqUpdateRiderPreferences) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{10}
}

func (x *RqUpdateRiderPreferences) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RqUpdateRiderPreferences) GetPreferredVehicleType() *RqEnum {
	if x != nil {
		return x.PreferredVehicleType
	}
	return nil
}

func (x *RqUpdateRiderPreferences) GetInstantMatchEnabled() bool {
	if x != nil {
		return x.InstantMatchEnabled
	}
	return false
}

func (x *RqUpdateRiderPreferences) GetPaymentMethod() *RqEnum {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *RqUpdateRiderPreferences) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *RqUpdateRiderPreferences) GetLanguage() *RqEnum {
	if x != nil {
		return x.Language
	}
	return nil
}

// Update rider preferences response
type RsUpdateRiderPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RsUpdateRiderPreferences) Reset() {
	*x = RsUpdateRiderPreferences{}
	mi := &file_rider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsUpdateRiderPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsUpdateRiderPreferences) ProtoMessage() {}

func (x *RsUpdateRiderPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsUpdateRiderPreferences.ProtoReflect.Descriptor instead.
func (*RsUpdateRiderPreferences) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{11}
}

func (x *RsUpdateRiderPreferences) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RsUpdateRiderPreferences) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rider_proto protoreflect.FileDescriptor

const file_rider_proto_rawDesc = "" +
	"\n" +
	"\vrider.proto\x12\x05rider\"Z\n" +
	"\x04Enum\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\")\n" +
	"\x06RsEnum\x12\x1f\n" +
	"\x04enum\x18\x01 \x03(\v2\v.rider.EnumR\x04enum\"%\n" +
	"\x06RqEnum\x12\x1b\n" +
	"\tenum_type\x18\x01 \x01(\tR\benumType\"+\n" +
	"\x0eRqGetRiderInfo\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\"\xb2\x02\n" +
	"\x0eRsGetRiderInfo\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\x12C\n" +
	"\x16preferred_vehicle_type\x18\x06 \x01(\v2\r.rider.RsEnumR\x14preferredVehicleType\x122\n" +
	"\x15instant_match_enabled\x18\a \x01(\bR\x13instantMatchEnabled\x124\n" +
	"\x0epayment_method\x18\b \x01(\v2\r.rider.RsEnumR\rpaymentMethod\"[\n" +
	"\x10RqGetTripHistory\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"]\n" +
	"\x10RsGetTripHistory\x12(\n" +
	"\x05trips\x18\x01 \x03(\v2\x12.rider.TripSummaryR\x05trips\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xad\x03\n" +
	"\vTripSummary\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vdriver_name\x18\x03 \x01(\tR\n" +
	"driverName\x120\n" +
	"\fvehicle_type\x18\x04 \x01(\v2\r.rider.RsEnumR\vvehicleType\x12%\n" +
	"\x0estart_latitude\x18\x05 \x01(\x01R\rstartLatitude\x12'\n" +
	"\x0fstart_longitude\x18\x06 \x01(\x01R\x0estartLongitude\x12!\n" +
	"\fend_latitude\x18\a \x01(\x01R\vendLatitude\x12#\n" +
	"\rend_longitude\x18\b \x01(\x01R\fendLongitude\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12%\n" +
	"\x06status\x18\n" +
	" \x01(\v2\r.rider.RsEnumR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\f \x01(\tR\vcompletedAt\"2\n" +
	"\x15RqGetRiderPreferences\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\"\xc1\x02\n" +
	"\x15RsGetRiderPreferences\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12C\n" +
	"\x16preferred_vehicle_type\x18\x02 \x01(\v2\r.rider.RsEnumR\x14preferredVehicleType\x122\n" +
	"\x15instant_match_enabled\x18\x03 \x01(\bR\x13instantMatchEnabled\x124\n" +
	"\x0epayment_method\x18\x04 \x01(\v2\r.rider.RsEnumR\rpaymentMethod\x123\n" +
	"\x15notifications_enabled\x18\x05 \x01(\bR\x14notificationsEnabled\x12)\n" +
	"\blanguage\x18\x06 \x01(\v2\r.rider.RsEnumR\blanguage\"\xc4\x02\n" +
	"\x18RqUpdateRiderPreferences\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12C\n" +
	"\x16preferred_vehicle_type\x18\x02 \x01(\v2\r.rider.RqEnumR\x14preferredVehicleType\x122\n" +
	"\x15instant_match_enabled\x18\x03 \x01(\bR\x13instantMatchEnabled\x124\n" +
	"\x0epayment_method\x18\x04 \x01(\v2\r.rider.RqEnumR\rpaymentMethod\x123\n" +
	"\x15notifications_enabled\x18\x05 \x01(\bR\x14notificationsEnabled\x12)\n" +
	"\blanguage\x18\x06 \x01(\v2\r.rider.RqEnumR\blanguage\"N\n" +
	"\x18RsUpdateRiderPreferences\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc7\x02\n" +
	"\fRiderService\x12>\n" +
	"\fGetRiderInfo\x12\x15.rider.RqGetRiderInfo\x1a\x15.rider.RsGetRiderInfo\"\x00\x12D\n" +
	"\x0eGetTripHistory\x12\x17.rider.RqGetTripHistory\x1a\x17.rider.RsGetTripHistory\"\x00\x12S\n" +
	"\x13GetRiderPreferences\x12\x1c.rider.RqGetRiderPreferences\x1a\x1c.rider.RsGetRiderPreferences\"\x00\x12\\\n" +
	"\x16UpdateRiderPreferences\x12\x1f.rider.RqUpdateRiderPreferences\x1a\x1f.rider.RsUpdateRiderPreferences\"\x00B\x1dZ\x1bcommon/genproto/rider;riderb\x06proto3"

var (
	file_rider_proto_rawDescOnce sync.Once
	file_rider_proto_rawDescData []byte
)

func file_rider_proto_rawDescGZIP() []byte {
	file_rider_proto_rawDescOnce.Do(func() {
		file_rider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)))
	})
	return file_rider_proto_rawDescData
}

var file_rider_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rider_proto_goTypes = []any{
	(*Enum)(nil),                     // 0: rider.Enum
	(*RsEnum)(nil),                   // 1: rider.RsEnum
	(*RqEnum)(nil),                   // 2: rider.RqEnum
	(*RqGetRiderInfo)(nil),           // 3: rider.RqGetRiderInfo
	(*RsGetRiderInfo)(nil),           // 4: rider.RsGetRiderInfo
	(*RqGetTripHistory)(nil),         // 5: rider.RqGetTripHistory
	(*RsGetTripHistory)(nil),         // 6: rider.RsGetTripHistory
	(*TripSummary)(nil),              // 7: rider.TripSummary
	(*RqGetRiderPreferences)(nil),    // 8: rider.RqGetRiderPreferences
	(*RsGetRiderPreferences)(nil),    // 9: rider.RsGetRiderPreferences
	(*RqUpdateRiderPreferences)(nil), // 10: rider.RqUpdateRiderPreferences
	(*RsUpdateRiderPreferences)(nil), // 11: rider.RsUpdateRiderPreferences
}
var file_rider_proto_depIdxs = []int32{
	0,  // 0: rider.RsEnum.enum:type_name -> rider.Enum
	1,  // 1: rider.RsGetRiderInfo.preferred_vehicle_type:type_name -> rider.RsEnum
	1,  // 2: rider.RsGetRiderInfo.payment_method:type_name -> rider.RsEnum
	7,  // 3: rider.RsGetTripHistory.trips:type_name -> rider.TripSummary
	1,  // 4: rider.TripSummary.vehicle_type:type_name -> rider.RsEnum
	1,  // 5: rider.TripSummary.status:type_name -> rider.RsEnum
	1,  // 6: rider.RsGetRiderPreferences.preferred_vehicle_type:type_name -> rider.RsEnum
	1,  // 7: rider.RsGetRiderPreferences.payment_method:type_name -> rider.RsEnum
	1,  // 8: rider.RsGetRiderPreferences.language:type_name -> rider.RsEnum
	2,  // 9: rider.RqUpdateRiderPreferences.preferred_vehicle_type:type_name -> rider.RqEnum
	2,  // 10: rider.RqUpdateRiderPreferences.payment_method:type_name -> rider.RqEnum
	2,  // 11: rider.RqUpdateRiderPreferences.language:type_name -> rider.RqEnum
	3,  // 12: rider.RiderService.GetRiderInfo:input_type -> rider.RqGetRiderInfo
	5,  // 13: rider.RiderService.GetTripHistory:input_type -> rider.RqGetTripHistory
	8,  // 14: rider.RiderService.GetRiderPreferences:input_type -> rider.RqGetRiderPreferences
	10, // 15: rider.RiderService.UpdateRiderPreferences:input_type -> rider.RqUpdateRiderPreferences
	4,  // 16: rider.RiderService.GetRiderInfo:output_type -> rider.RsGetRiderInfo
	6,  // 17: rider.RiderService.GetTripHistory:output_type -> rider.RsGetTripHistory
	9,  // 18: rider.RiderService.GetRiderPreferences:output_type -> rider.RsGetRiderPreferences
	11, // 19: rider.RiderService.UpdateRiderPreferences:output_type -> rider.RsUpdateRiderPreferences
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rider_proto_init() }
func file_rider_proto_init() {
	if File_rider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rider_proto_goTypes,
		DependencyIndexes: file_rider_proto_depIdxs,
		MessageInfos:      file_rider_proto_msgTypes,
	}.Build()
	File_rider_proto = out.File
	file_rider_proto_goTypes = nil
	file_rider_proto_depIdxs = nil
}
