// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnumType      string                 `protobuf:"bytes,1,opt,name=enum_type,json=enumType,proto3" json:"enum_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumRequest) Reset() {
	*x = EnumRequest{}
	mi := &file_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumRequest) ProtoMessage() {}

func (x *EnumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumRequest.ProtoReflect.Descriptor instead.
func (*EnumRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *EnumRequest) GetEnumType() string {
	if x != nil {
		return x.EnumType
	}
	return ""
}

// Enum value representation
type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *Enum) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Enum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enum) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Enum) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Enum response
type EnumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enum          []*Enum                `protobuf:"bytes,1,rep,name=enum,proto3" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumResponse) Reset() {
	*x = EnumResponse{}
	mi := &file_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumResponse) ProtoMessage() {}

func (x *EnumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumResponse.ProtoReflect.Descriptor instead.
func (*EnumResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *EnumResponse) GetEnum() []*Enum {
	if x != nil {
		return x.Enum
	}
	return nil
}

// Payment message
type Payment struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TripId               string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RiderId              string                 `protobuf:"bytes,3,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId             string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	CommissionAmount     float64                `protobuf:"fixed64,6,opt,name=commission_amount,json=commissionAmount,proto3" json:"commission_amount,omitempty"`
	DriverEarning        float64                `protobuf:"fixed64,7,opt,name=driver_earning,json=driverEarning,proto3" json:"driver_earning,omitempty"`
	PaymentMethod        *EnumResponse          `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Status               *EnumResponse          `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	GatewayTransactionId string                 `protobuf:"bytes,10,opt,name=gateway_transaction_id,json=gatewayTransactionId,proto3" json:"gateway_transaction_id,omitempty"`
	GatewayResponse      string                 `protobuf:"bytes,11,opt,name=gateway_response,json=gatewayResponse,proto3" json:"gateway_response,omitempty"`
	ProcessedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	FailedAt             *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	FailureReason        string                 `protobuf:"bytes,14,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	RefundReason         string                 `protobuf:"bytes,15,opt,name=refund_reason,json=refundReason,proto3" json:"refund_reason,omitempty"`
	RefundedAt           *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	RefundAmount         float64                `protobuf:"fixed64,17,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *Payment) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *Payment) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCommissionAmount() float64 {
	if x != nil {
		return x.CommissionAmount
	}
	return 0
}

func (x *Payment) GetDriverEarning() float64 {
	if x != nil {
		return x.DriverEarning
	}
	return 0
}

func (x *Payment) GetPaymentMethod() *EnumResponse {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *Payment) GetStatus() *EnumResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Payment) GetGatewayTransactionId() string {
	if x != nil {
		return x.GatewayTransactionId
	}
	return ""
}

func (x *Payment) GetGatewayResponse() string {
	if x != nil {
		return x.GatewayResponse
	}
	return ""
}

func (x *Payment) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *Payment) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *Payment) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Payment) GetRefundReason() string {
	if x != nil {
		return x.RefundReason
	}
	return ""
}

func (x *Payment) GetRefundedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefundedAt
	}
	return nil
}

func (x *Payment) GetRefundAmount() float64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Transaction message
type Transaction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId            string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	GatewayTransactionId string                 `protobuf:"bytes,3,opt,name=gateway_transaction_id,json=gatewayTransactionId,proto3" json:"gateway_transaction_id,omitempty"`
	Type                 *EnumResponse          `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status               *EnumResponse          `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	GatewayResponse      string                 `protobuf:"bytes,7,opt,name=gateway_response,json=gatewayResponse,proto3" json:"gateway_response,omitempty"`
	ProcessedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	FailureReason        string                 `protobuf:"bytes,9,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Metadata             string                 `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON string
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Transaction) GetGatewayTransactionId() string {
	if x != nil {
		return x.GatewayTransactionId
	}
	return ""
}

func (x *Transaction) GetType() *EnumResponse {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetStatus() *EnumResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Transaction) GetGatewayResponse() string {
	if x != nil {
		return x.GatewayResponse
	}
	return ""
}

func (x *Transaction) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *Transaction) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Transaction) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Refund message
type Refund struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId       string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status          *EnumResponse          `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Reason          string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	GatewayRefundId string                 `protobuf:"bytes,6,opt,name=gateway_refund_id,json=gatewayRefundId,proto3" json:"gateway_refund_id,omitempty"`
	GatewayResponse string                 `protobuf:"bytes,7,opt,name=gateway_response,json=gatewayResponse,proto3" json:"gateway_response,omitempty"`
	ProcessedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	FailureReason   string                 `protobuf:"bytes,9,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	RequestedBy     string                 `protobuf:"bytes,10,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Refund) Reset() {
	*x = Refund{}
	mi := &file_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refund) ProtoMessage() {}

func (x *Refund) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refund.ProtoReflect.Descriptor instead.
func (*Refund) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *Refund) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Refund) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Refund) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Refund) GetStatus() *EnumResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Refund) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Refund) GetGatewayRefundId() string {
	if x != nil {
		return x.GatewayRefundId
	}
	return ""
}

func (x *Refund) GetGatewayResponse() string {
	if x != nil {
		return x.GatewayResponse
	}
	return ""
}

func (x *Refund) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *Refund) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Refund) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *Refund) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Refund) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Wallet message
type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      *EnumResponse          `protobuf:"bytes,3,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	FrozenBalance float64                `protobuf:"fixed64,5,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"`
	Status        *EnumResponse          `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Wallet) GetUserType() *EnumResponse {
	if x != nil {
		return x.UserType
	}
	return nil
}

func (x *Wallet) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Wallet) GetFrozenBalance() float64 {
	if x != nil {
		return x.FrozenBalance
	}
	return 0
}

func (x *Wallet) GetStatus() *EnumResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Wallet) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Wallet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Wallet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Wallet Transaction message
type WalletTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Type          *EnumResponse          `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceBefore float64                `protobuf:"fixed64,5,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"`
	BalanceAfter  float64                `protobuf:"fixed64,6,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,8,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType string                 `protobuf:"bytes,9,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletTransaction) Reset() {
	*x = WalletTransaction{}
	mi := &file_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletTransaction) ProtoMessage() {}

func (x *WalletTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletTransaction.ProtoReflect.Descriptor instead.
func (*WalletTransaction) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *WalletTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WalletTransaction) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletTransaction) GetType() *EnumResponse {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *WalletTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WalletTransaction) GetBalanceBefore() float64 {
	if x != nil {
		return x.BalanceBefore
	}
	return 0
}

func (x *WalletTransaction) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *WalletTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WalletTransaction) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *WalletTransaction) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *WalletTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WalletTransaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ProcessPayment
type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod *EnumRequest           `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessPaymentRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessPaymentRequest) GetPaymentMethod() *EnumRequest {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *ProcessPaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProcessPaymentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProcessPaymentResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payment              *Payment               `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	GatewayTransactionId string                 `protobuf:"bytes,4,opt,name=gateway_transaction_id,json=gatewayTransactionId,proto3" json:"gateway_transaction_id,omitempty"`
	PaymentUrl           string                 `protobuf:"bytes,5,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"` // For redirect-based payments
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_payment_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *ProcessPaymentResponse) GetGatewayTransactionId() string {
	if x != nil {
		return x.GatewayTransactionId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

// GetPaymentStatus
type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"` // Alternative identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_payment_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{10}
}

func (x *GetPaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetPaymentStatusRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type GetPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payment       *Payment               `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_payment_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{11}
}

func (x *GetPaymentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPaymentStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPaymentStatusResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// ProcessRefund
type ProcessRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"` // Optional, full refund if omitted
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,4,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRefundRequest) Reset() {
	*x = ProcessRefundRequest{}
	mi := &file_payment_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRefundRequest) ProtoMessage() {}

func (x *ProcessRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRefundRequest.ProtoReflect.Descriptor instead.
func (*ProcessRefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessRefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ProcessRefundRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessRefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProcessRefundRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type ProcessRefundResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Refund          *Refund                `protobuf:"bytes,3,opt,name=refund,proto3" json:"refund,omitempty"`
	GatewayRefundId string                 `protobuf:"bytes,4,opt,name=gateway_refund_id,json=gatewayRefundId,proto3" json:"gateway_refund_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessRefundResponse) Reset() {
	*x = ProcessRefundResponse{}
	mi := &file_payment_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRefundResponse) ProtoMessage() {}

func (x *ProcessRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRefundResponse.ProtoReflect.Descriptor instead.
func (*ProcessRefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{13}
}

func (x *ProcessRefundResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessRefundResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessRefundResponse) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

func (x *ProcessRefundResponse) GetGatewayRefundId() string {
	if x != nil {
		return x.GatewayRefundId
	}
	return ""
}

// GetPaymentHistory
type GetPaymentHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      *EnumRequest           `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        *EnumRequest           `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentHistoryRequest) Reset() {
	*x = GetPaymentHistoryRequest{}
	mi := &file_payment_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentHistoryRequest) ProtoMessage() {}

func (x *GetPaymentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{14}
}

func (x *GetPaymentHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPaymentHistoryRequest) GetUserType() *EnumRequest {
	if x != nil {
		return x.UserType
	}
	return nil
}

func (x *GetPaymentHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPaymentHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPaymentHistoryRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetPaymentHistoryRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetPaymentHistoryRequest) GetStatus() *EnumRequest {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetPaymentHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payments      []*Payment             `protobuf:"bytes,3,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentHistoryResponse) Reset() {
	*x = GetPaymentHistoryResponse{}
	mi := &file_payment_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentHistoryResponse) ProtoMessage() {}

func (x *GetPaymentHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentHistoryResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{15}
}

func (x *GetPaymentHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPaymentHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPaymentHistoryResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetPaymentHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPaymentHistoryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPaymentHistoryResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// HandleWebhook
type HandleWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // gateway name
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // JSON string
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleWebhookRequest) Reset() {
	*x = HandleWebhookRequest{}
	mi := &file_payment_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleWebhookRequest) ProtoMessage() {}

func (x *HandleWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandleWebhookRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{16}
}

func (x *HandleWebhookRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HandleWebhookRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HandleWebhookRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *HandleWebhookRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *HandleWebhookRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HandleWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"` // JSON response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleWebhookResponse) Reset() {
	*x = HandleWebhookResponse{}
	mi := &file_payment_payment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleWebhookResponse) ProtoMessage() {}

func (x *HandleWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleWebhookResponse.ProtoReflect.Descriptor instead.
func (*HandleWebhookResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{17}
}

func (x *HandleWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HandleWebhookResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type GetWalletBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      *EnumRequest           `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceRequest) Reset() {
	*x = GetWalletBalanceRequest{}
	mi := &file_payment_payment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceRequest) ProtoMessage() {}

func (x *GetWalletBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{18}
}

func (x *GetWalletBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWalletBalanceRequest) GetUserType() *EnumRequest {
	if x != nil {
		return x.UserType
	}
	return nil
}

type GetWalletBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Wallet        *Wallet                `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceResponse) Reset() {
	*x = GetWalletBalanceResponse{}
	mi := &file_payment_payment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceResponse) ProtoMessage() {}

func (x *GetWalletBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{19}
}

func (x *GetWalletBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetWalletBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetWalletBalanceResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type TopupWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      *EnumRequest           `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod *EnumRequest           `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupWalletRequest) Reset() {
	*x = TopupWalletRequest{}
	mi := &file_payment_payment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupWalletRequest) ProtoMessage() {}

func (x *TopupWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupWalletRequest.ProtoReflect.Descriptor instead.
func (*TopupWalletRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{20}
}

func (x *TopupWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TopupWalletRequest) GetUserType() *EnumRequest {
	if x != nil {
		return x.UserType
	}
	return nil
}

func (x *TopupWalletRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TopupWalletRequest) GetPaymentMethod() *EnumRequest {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *TopupWalletRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TopupWalletRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TopupWalletResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Wallet               *Wallet                `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	GatewayTransactionId string                 `protobuf:"bytes,4,opt,name=gateway_transaction_id,json=gatewayTransactionId,proto3" json:"gateway_transaction_id,omitempty"`
	PaymentUrl           string                 `protobuf:"bytes,5,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TopupWalletResponse) Reset() {
	*x = TopupWalletResponse{}
	mi := &file_payment_payment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupWalletResponse) ProtoMessage() {}

func (x *TopupWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupWalletResponse.ProtoReflect.Descriptor instead.
func (*TopupWalletResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{21}
}

func (x *TopupWalletResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TopupWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TopupWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

func (x *TopupWalletResponse) GetGatewayTransactionId() string {
	if x != nil {
		return x.GatewayTransactionId
	}
	return ""
}

func (x *TopupWalletResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type WithdrawFromWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      *EnumRequest           `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawFromWalletRequest) Reset() {
	*x = WithdrawFromWalletRequest{}
	mi := &file_payment_payment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawFromWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawFromWalletRequest) ProtoMessage() {}

func (x *WithdrawFromWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawFromWalletRequest.ProtoReflect.Descriptor instead.
func (*WithdrawFromWalletRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{22}
}

func (x *WithdrawFromWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WithdrawFromWalletRequest) GetUserType() *EnumRequest {
	if x != nil {
		return x.UserType
	}
	return nil
}

func (x *WithdrawFromWalletRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawFromWalletRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WithdrawFromWalletRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WithdrawFromWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Wallet        *Wallet                `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Transaction   *WalletTransaction     `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawFromWalletResponse) Reset() {
	*x = WithdrawFromWalletResponse{}
	mi := &file_payment_payment_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawFromWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawFromWalletResponse) ProtoMessage() {}

func (x *WithdrawFromWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawFromWalletResponse.ProtoReflect.Descriptor instead.
func (*WithdrawFromWalletResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{23}
}

func (x *WithdrawFromWalletResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WithdrawFromWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WithdrawFromWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

func (x *WithdrawFromWalletResponse) GetTransaction() *WalletTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetWalletTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      *EnumRequest           `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Type          *EnumRequest           `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletTransactionsRequest) Reset() {
	*x = GetWalletTransactionsRequest{}
	mi := &file_payment_payment_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletTransactionsRequest) ProtoMessage() {}

func (x *GetWalletTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetWalletTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{24}
}

func (x *GetWalletTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWalletTransactionsRequest) GetUserType() *EnumRequest {
	if x != nil {
		return x.UserType
	}
	return nil
}

func (x *GetWalletTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetWalletTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWalletTransactionsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetWalletTransactionsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetWalletTransactionsRequest) GetType() *EnumRequest {
	if x != nil {
		return x.Type
	}
	return nil
}

type GetWalletTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Transactions  []*WalletTransaction   `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletTransactionsResponse) Reset() {
	*x = GetWalletTransactionsResponse{}
	mi := &file_payment_payment_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletTransactionsResponse) ProtoMessage() {}

func (x *GetWalletTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetWalletTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{25}
}

func (x *GetWalletTransactionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetWalletTransactionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetWalletTransactionsResponse) GetTransactions() []*WalletTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetWalletTransactionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetWalletTransactionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetWalletTransactionsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_payment_payment_proto protoreflect.FileDescriptor

const file_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x15payment/payment.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\vEnumRequest\x12\x1b\n" +
	"\tenum_type\x18\x01 \x01(\tR\benumType\"Z\n" +
	"\x04Enum\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"1\n" +
	"\fEnumResponse\x12!\n" +
	"\x04enum\x18\x01 \x03(\v2\r.payment.EnumR\x04enum\"\xc0\x06\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x19\n" +
	"\brider_id\x18\x03 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12+\n" +
	"\x11commission_amount\x18\x06 \x01(\x01R\x10commissionAmount\x12%\n" +
	"\x0edriver_earning\x18\a \x01(\x01R\rdriverEarning\x12<\n" +
	"\x0epayment_method\x18\b \x01(\v2\x15.payment.EnumResponseR\rpaymentMethod\x12-\n" +
	"\x06status\x18\t \x01(\v2\x15.payment.EnumResponseR\x06status\x124\n" +
	"\x16gateway_transaction_id\x18\n" +
	" \x01(\tR\x14gatewayTransactionId\x12)\n" +
	"\x10gateway_response\x18\v \x01(\tR\x0fgatewayResponse\x12=\n" +
	"\fprocessed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x127\n" +
	"\tfailed_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12%\n" +
	"\x0efailure_reason\x18\x0e \x01(\tR\rfailureReason\x12#\n" +
	"\rrefund_reason\x18\x0f \x01(\tR\frefundReason\x12;\n" +
	"\vrefunded_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"refundedAt\x12#\n" +
	"\rrefund_amount\x18\x11 \x01(\x01R\frefundAmount\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x87\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x124\n" +
	"\x16gateway_transaction_id\x18\x03 \x01(\tR\x14gatewayTransactionId\x12)\n" +
	"\x04type\x18\x04 \x01(\v2\x15.payment.EnumResponseR\x04type\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12-\n" +
	"\x06status\x18\x06 \x01(\v2\x15.payment.EnumResponseR\x06status\x12)\n" +
	"\x10gateway_response\x18\a \x01(\tR\x0fgatewayResponse\x12=\n" +
	"\fprocessed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12%\n" +
	"\x0efailure_reason\x18\t \x01(\tR\rfailureReason\x12\x1a\n" +
	"\bmetadata\x18\n" +
	" \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xec\x03\n" +
	"\x06Refund\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12-\n" +
	"\x06status\x18\x04 \x01(\v2\x15.payment.EnumResponseR\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12*\n" +
	"\x11gateway_refund_id\x18\x06 \x01(\tR\x0fgatewayRefundId\x12)\n" +
	"\x10gateway_response\x18\a \x01(\tR\x0fgatewayResponse\x12=\n" +
	"\fprocessed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12%\n" +
	"\x0efailure_reason\x18\t \x01(\tR\rfailureReason\x12!\n" +
	"\frequested_by\x18\n" +
	" \x01(\tR\vrequestedBy\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe7\x02\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x122\n" +
	"\tuser_type\x18\x03 \x01(\v2\x15.payment.EnumResponseR\buserType\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\x12%\n" +
	"\x0efrozen_balance\x18\x05 \x01(\x01R\rfrozenBalance\x12-\n" +
	"\x06status\x18\x06 \x01(\v2\x15.payment.EnumResponseR\x06status\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb1\x03\n" +
	"\x11WalletTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12)\n" +
	"\x04type\x18\x03 \x01(\v2\x15.payment.EnumResponseR\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12%\n" +
	"\x0ebalance_before\x18\x05 \x01(\x01R\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\x06 \x01(\x01R\fbalanceAfter\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12!\n" +
	"\freference_id\x18\b \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\t \x01(\tR\rreferenceType\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe0\x02\n" +
	"\x15ProcessPaymentRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12;\n" +
	"\x0epayment_method\x18\x05 \x01(\v2\x14.payment.EnumRequestR\rpaymentMethod\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12H\n" +
	"\bmetadata\x18\a \x03(\v2,.payment.ProcessPaymentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x16ProcessPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\apayment\x18\x03 \x01(\v2\x10.payment.PaymentR\apayment\x124\n" +
	"\x16gateway_transaction_id\x18\x04 \x01(\tR\x14gatewayTransactionId\x12\x1f\n" +
	"\vpayment_url\x18\x05 \x01(\tR\n" +
	"paymentUrl\"Q\n" +
	"\x17GetPaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\"z\n" +
	"\x18GetPaymentStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\apayment\x18\x03 \x01(\v2\x10.payment.PaymentR\apayment\"\x88\x01\n" +
	"\x14ProcessRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\frequested_by\x18\x04 \x01(\tR\vrequestedBy\"\xa0\x01\n" +
	"\x15ProcessRefundResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x06refund\x18\x03 \x01(\v2\x0f.payment.RefundR\x06refund\x12*\n" +
	"\x11gateway_refund_id\x18\x04 \x01(\tR\x0fgatewayRefundId\"\xb0\x02\n" +
	"\x18GetPaymentHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\tuser_type\x18\x02 \x01(\v2\x14.payment.EnumRequestR\buserType\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12,\n" +
	"\x06status\x18\a \x01(\v2\x14.payment.EnumRequestR\x06status\"\xbd\x01\n" +
	"\x19GetPaymentHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\bpayments\x18\x03 \x03(\v2\x10.payment.PaymentR\bpayments\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\x87\x02\n" +
	"\x14HandleWebhookRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12D\n" +
	"\aheaders\x18\x05 \x03(\v2*.payment.HandleWebhookRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x15HandleWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\"e\n" +
	"\x17GetWalletBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\tuser_type\x18\x02 \x01(\v2\x14.payment.EnumRequestR\buserType\"w\n" +
	"\x18GetWalletBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x06wallet\x18\x03 \x01(\v2\x0f.payment.WalletR\x06wallet\"\xd5\x02\n" +
	"\x12TopupWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\tuser_type\x18\x02 \x01(\v2\x14.payment.EnumRequestR\buserType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12;\n" +
	"\x0epayment_method\x18\x04 \x01(\v2\x14.payment.EnumRequestR\rpaymentMethod\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12E\n" +
	"\bmetadata\x18\x06 \x03(\v2).payment.TopupWalletRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x13TopupWalletResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x06wallet\x18\x03 \x01(\v2\x0f.payment.WalletR\x06wallet\x124\n" +
	"\x16gateway_transaction_id\x18\x04 \x01(\tR\x14gatewayTransactionId\x12\x1f\n" +
	"\vpayment_url\x18\x05 \x01(\tR\n" +
	"paymentUrl\"\xac\x02\n" +
	"\x19WithdrawFromWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\tuser_type\x18\x02 \x01(\v2\x14.payment.EnumRequestR\buserType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12L\n" +
	"\bmetadata\x18\x05 \x03(\v20.payment.WithdrawFromWalletRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x1aWithdrawFromWalletResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x06wallet\x18\x03 \x01(\v2\x0f.payment.WalletR\x06wallet\x12<\n" +
	"\vtransaction\x18\x04 \x01(\v2\x1a.payment.WalletTransactionR\vtransaction\"\xb0\x02\n" +
	"\x1cGetWalletTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\tuser_type\x18\x02 \x01(\v2\x14.payment.EnumRequestR\buserType\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12(\n" +
	"\x04type\x18\a \x01(\v2\x14.payment.EnumRequestR\x04type\"\xd3\x01\n" +
	"\x1dGetWalletTransactionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\ftransactions\x18\x03 \x03(\v2\x1a.payment.WalletTransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit2\xb8\x03\n" +
	"\x0ePaymentService\x12Q\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\x12W\n" +
	"\x10GetPaymentStatus\x12 .payment.GetPaymentStatusRequest\x1a!.payment.GetPaymentStatusResponse\x12N\n" +
	"\rProcessRefund\x12\x1d.payment.ProcessRefundRequest\x1a\x1e.payment.ProcessRefundResponse\x12Z\n" +
	"\x11GetPaymentHistory\x12!.payment.GetPaymentHistoryRequest\x1a\".payment.GetPaymentHistoryResponse\x12N\n" +
	"\rHandleWebhook\x12\x1d.payment.HandleWebhookRequest\x1a\x1e.payment.HandleWebhookResponse2\xf9\x02\n" +
	"\rWalletService\x12W\n" +
	"\x10GetWalletBalance\x12 .payment.GetWalletBalanceRequest\x1a!.payment.GetWalletBalanceResponse\x12H\n" +
	"\vTopupWallet\x12\x1b.payment.TopupWalletRequest\x1a\x1c.payment.TopupWalletResponse\x12]\n" +
	"\x12WithdrawFromWallet\x12\".payment.WithdrawFromWalletRequest\x1a#.payment.WithdrawFromWalletResponse\x12f\n" +
	"\x15GetWalletTransactions\x12%.payment.GetWalletTransactionsRequest\x1a&.payment.GetWalletTransactionsResponseBBZ@github.com/mihirk-khode/motocabz-common/genproto/payment;paymentb\x06proto3"

var (
	file_payment_payment_proto_rawDescOnce sync.Once
	file_payment_payment_proto_rawDescData []byte
)

func file_payment_payment_proto_rawDescGZIP() []byte {
	file_payment_payment_proto_rawDescOnce.Do(func() {
		file_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)))
	})
	return file_payment_payment_proto_rawDescData
}

var file_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_payment_payment_proto_goTypes = []any{
	(*EnumRequest)(nil),                   // 0: payment.EnumRequest
	(*Enum)(nil),                          // 1: payment.Enum
	(*EnumResponse)(nil),                  // 2: payment.EnumResponse
	(*Payment)(nil),                       // 3: payment.Payment
	(*Transaction)(nil),                   // 4: payment.Transaction
	(*Refund)(nil),                        // 5: payment.Refund
	(*Wallet)(nil),                        // 6: payment.Wallet
	(*WalletTransaction)(nil),             // 7: payment.WalletTransaction
	(*ProcessPaymentRequest)(nil),         // 8: payment.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),        // 9: payment.ProcessPaymentResponse
	(*GetPaymentStatusRequest)(nil),       // 10: payment.GetPaymentStatusRequest
	(*GetPaymentStatusResponse)(nil),      // 11: payment.GetPaymentStatusResponse
	(*ProcessRefundRequest)(nil),          // 12: payment.ProcessRefundRequest
	(*ProcessRefundResponse)(nil),         // 13: payment.ProcessRefundResponse
	(*GetPaymentHistoryRequest)(nil),      // 14: payment.GetPaymentHistoryRequest
	(*GetPaymentHistoryResponse)(nil),     // 15: payment.GetPaymentHistoryResponse
	(*HandleWebhookRequest)(nil),          // 16: payment.HandleWebhookRequest
	(*HandleWebhookResponse)(nil),         // 17: payment.HandleWebhookResponse
	(*GetWalletBalanceRequest)(nil),       // 18: payment.GetWalletBalanceRequest
	(*GetWalletBalanceResponse)(nil),      // 19: payment.GetWalletBalanceResponse
	(*TopupWalletRequest)(nil),            // 20: payment.TopupWalletRequest
	(*TopupWalletResponse)(nil),           // 21: payment.TopupWalletResponse
	(*WithdrawFromWalletRequest)(nil),     // 22: payment.WithdrawFromWalletRequest
	(*WithdrawFromWalletResponse)(nil),    // 23: payment.WithdrawFromWalletResponse
	(*GetWalletTransactionsRequest)(nil),  // 24: payment.GetWalletTransactionsRequest
	(*GetWalletTransactionsResponse)(nil), // 25: payment.GetWalletTransactionsResponse
	nil,                                   // 26: payment.ProcessPaymentRequest.MetadataEntry
	nil,                                   // 27: payment.HandleWebhookRequest.HeadersEntry
	nil,                                   // 28: payment.TopupWalletRequest.MetadataEntry
	nil,                                   // 29: payment.WithdrawFromWalletRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),         // 30: google.protobuf.Timestamp
}
var file_payment_payment_proto_depIdxs = []int32{
	1,  // 0: payment.EnumResponse.enum:type_name -> payment.Enum
	2,  // 1: payment.Payment.payment_method:type_name -> payment.EnumResponse
	2,  // 2: payment.Payment.status:type_name -> payment.EnumResponse
	30, // 3: payment.Payment.processed_at:type_name -> google.protobuf.Timestamp
	30, // 4: payment.Payment.failed_at:type_name -> google.protobuf.Timestamp
	30, // 5: payment.Payment.refunded_at:type_name -> google.protobuf.Timestamp
	30, // 6: payment.Payment.created_at:type_name -> google.protobuf.Timestamp
	30, // 7: payment.Payment.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 8: payment.Transaction.type:type_name -> payment.EnumResponse
	2,  // 9: payment.Transaction.status:type_name -> payment.EnumResponse
	30, // 10: payment.Transaction.processed_at:type_name -> google.protobuf.Timestamp
	30, // 11: payment.Transaction.created_at:type_name -> google.protobuf.Timestamp
	30, // 12: payment.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 13: payment.Refund.status:type_name -> payment.EnumResponse
	30, // 14: payment.Refund.processed_at:type_name -> google.protobuf.Timestamp
	30, // 15: payment.Refund.created_at:type_name -> google.protobuf.Timestamp
	30, // 16: payment.Refund.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 17: payment.Wallet.user_type:type_name -> payment.EnumResponse
	2,  // 18: payment.Wallet.status:type_name -> payment.EnumResponse
	30, // 19: payment.Wallet.created_at:type_name -> google.protobuf.Timestamp
	30, // 20: payment.Wallet.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 21: payment.WalletTransaction.type:type_name -> payment.EnumResponse
	30, // 22: payment.WalletTransaction.created_at:type_name -> google.protobuf.Timestamp
	30, // 23: payment.WalletTransaction.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 24: payment.ProcessPaymentRequest.payment_method:type_name -> payment.EnumRequest
	26, // 25: payment.ProcessPaymentRequest.metadata:type_name -> payment.ProcessPaymentRequest.MetadataEntry
	3,  // 26: payment.ProcessPaymentResponse.payment:type_name -> payment.Payment
	3,  // 27: payment.GetPaymentStatusResponse.payment:type_name -> payment.Payment
	5,  // 28: payment.ProcessRefundResponse.refund:type_name -> payment.Refund
	0,  // 29: payment.GetPaymentHistoryRequest.user_type:type_name -> payment.EnumRequest
	30, // 30: payment.GetPaymentHistoryRequest.start_date:type_name -> google.protobuf.Timestamp
	30, // 31: payment.GetPaymentHistoryRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 32: payment.GetPaymentHistoryRequest.status:type_name -> payment.EnumRequest
	3,  // 33: payment.GetPaymentHistoryResponse.payments:type_name -> payment.Payment
	27, // 34: payment.HandleWebhookRequest.headers:type_name -> payment.HandleWebhookRequest.HeadersEntry
	0,  // 35: payment.GetWalletBalanceRequest.user_type:type_name -> payment.EnumRequest
	6,  // 36: payment.GetWalletBalanceResponse.wallet:type_name -> payment.Wallet
	0,  // 37: payment.TopupWalletRequest.user_type:type_name -> payment.EnumRequest
	0,  // 38: payment.TopupWalletRequest.payment_method:type_name -> payment.EnumRequest
	28, // 39: payment.TopupWalletRequest.metadata:type_name -> payment.TopupWalletRequest.MetadataEntry
	6,  // 40: payment.TopupWalletResponse.wallet:type_name -> payment.Wallet
	0,  // 41: payment.WithdrawFromWalletRequest.user_type:type_name -> payment.EnumRequest
	29, // 42: payment.WithdrawFromWalletRequest.metadata:type_name -> payment.WithdrawFromWalletRequest.MetadataEntry
	6,  // 43: payment.WithdrawFromWalletResponse.wallet:type_name -> payment.Wallet
	7,  // 44: payment.WithdrawFromWalletResponse.transaction:type_name -> payment.WalletTransaction
	0,  // 45: payment.GetWalletTransactionsRequest.user_type:type_name -> payment.EnumRequest
	30, // 46: payment.GetWalletTransactionsRequest.start_date:type_name -> google.protobuf.Timestamp
	30, // 47: payment.GetWalletTransactionsRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 48: payment.GetWalletTransactionsRequest.type:type_name -> payment.EnumRequest
	7,  // 49: payment.GetWalletTransactionsResponse.transactions:type_name -> payment.WalletTransaction
	8,  // 50: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	10, // 51: payment.PaymentService.GetPaymentStatus:input_type -> payment.GetPaymentStatusRequest
	12, // 52: payment.PaymentService.ProcessRefund:input_type -> payment.ProcessRefundRequest
	14, // 53: payment.PaymentService.GetPaymentHistory:input_type -> payment.GetPaymentHistoryRequest
	16, // 54: payment.PaymentService.HandleWebhook:input_type -> payment.HandleWebhookRequest
	18, // 55: payment.WalletService.GetWalletBalance:input_type -> payment.GetWalletBalanceRequest
	20, // 56: payment.WalletService.TopupWallet:input_type -> payment.TopupWalletRequest
	22, // 57: payment.WalletService.WithdrawFromWallet:input_type -> payment.WithdrawFromWalletRequest
	24, // 58: payment.WalletService.GetWalletTransactions:input_type -> payment.GetWalletTransactionsRequest
	9,  // 59: payment.PaymentService.ProcessPayment:output_type -> payment.ProcessPaymentResponse
	11, // 60: payment.PaymentService.GetPaymentStatus:output_type -> payment.GetPaymentStatusResponse
	13, // 61: payment.PaymentService.ProcessRefund:output_type -> payment.ProcessRefundResponse
	15, // 62: payment.PaymentService.GetPaymentHistory:output_type -> payment.GetPaymentHistoryResponse
	17, // 63: payment.PaymentService.HandleWebhook:output_type -> payment.HandleWebhookResponse
	19, // 64: payment.WalletService.GetWalletBalance:output_type -> payment.GetWalletBalanceResponse
	21, // 65: payment.WalletService.TopupWallet:output_type -> payment.TopupWalletResponse
	23, // 66: payment.WalletService.WithdrawFromWallet:output_type -> payment.WithdrawFromWalletResponse
	25, // 67: payment.WalletService.GetWalletTransactions:output_type -> payment.GetWalletTransactionsResponse
	59, // [59:68] is the sub-list for method output_type
	50, // [50:59] is the sub-list for method input_type
	50, // [50:50] is the sub-list for extension type_name
	50, // [50:50] is the sub-list for extension extendee
	0,  // [0:50] is the sub-list for field type_name
}

func init() { file_payment_payment_proto_init() }
func file_payment_payment_proto_init() {
	if File_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_payment_payment_proto_goTypes,
		DependencyIndexes: file_payment_payment_proto_depIdxs,
		MessageInfos:      file_payment_payment_proto_msgTypes,
	}.Build()
	File_payment_payment_proto = out.File
	file_payment_payment_proto_goTypes = nil
	file_payment_payment_proto_depIdxs = nil
}
