// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: trip/trip.proto

package trip

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TripService_CreateTrip_FullMethodName        = "/trip.TripService/CreateTrip"
	TripService_SubmitBidOrOffer_FullMethodName  = "/trip.TripService/SubmitBidOrOffer"
	TripService_AcceptOffer_FullMethodName       = "/trip.TripService/AcceptOffer"
	TripService_GetTrip_FullMethodName           = "/trip.TripService/GetTrip"
	TripService_GetActiveTrips_FullMethodName    = "/trip.TripService/GetActiveTrips"
	TripService_AcceptTrip_FullMethodName        = "/trip.TripService/AcceptTrip"
	TripService_CancelTrip_FullMethodName        = "/trip.TripService/CancelTrip"
	TripService_CompleteTrip_FullMethodName      = "/trip.TripService/CompleteTrip"
	TripService_GetBiddingSession_FullMethodName = "/trip.TripService/GetBiddingSession"
	TripService_GetTripHistory_FullMethodName    = "/trip.TripService/GetTripHistory"
	TripService_IsTripActive_FullMethodName      = "/trip.TripService/IsTripActive"
	TripService_CreateRating_FullMethodName      = "/trip.TripService/CreateRating"
	TripService_GetRating_FullMethodName         = "/trip.TripService/GetRating"
	TripService_ListRating_FullMethodName        = "/trip.TripService/ListRating"
	TripService_DeleteRating_FullMethodName      = "/trip.TripService/DeleteRating"
	TripService_UpdateRating_FullMethodName      = "/trip.TripService/UpdateRating"
)

// TripServiceClient is the client API for TripService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripServiceClient interface {
	// Trips
	CreateTrip(ctx context.Context, in *TripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	SubmitBidOrOffer(ctx context.Context, in *BidOrOfferRequest, opts ...grpc.CallOption) (*BidOrOfferResponse, error)
	AcceptOffer(ctx context.Context, in *AcceptOfferRequest, opts ...grpc.CallOption) (*AcceptOfferResponse, error)
	GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	GetActiveTrips(ctx context.Context, in *TripFilterRequest, opts ...grpc.CallOption) (*ListTripResponse, error)
	AcceptTrip(ctx context.Context, in *AcceptTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*CancelTripResponse, error)
	CompleteTrip(ctx context.Context, in *CompleteTripRequest, opts ...grpc.CallOption) (*CompleteTripResponse, error)
	// Bidding Session
	GetBiddingSession(ctx context.Context, in *BiddingSessionFilterRequest, opts ...grpc.CallOption) (*BiddingSessionResponse, error)
	//Trip History
	GetTripHistory(ctx context.Context, in *TripHistoryFilterRequest, opts ...grpc.CallOption) (*TripHistoryResponse, error)
	IsTripActive(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	//Rating
	CreateRating(ctx context.Context, in *RatingRequest, opts ...grpc.CallOption) (*RatingResponse, error)
	GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*RatingResponse, error)
	ListRating(ctx context.Context, in *ListRatingRequest, opts ...grpc.CallOption) (*ListRatingResponse, error)
	DeleteRating(ctx context.Context, in *DeleteRatingRequest, opts ...grpc.CallOption) (*DeleteRatingResponse, error)
	UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*RatingResponse, error)
}

type tripServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServiceClient(cc grpc.ClientConnInterface) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) CreateTrip(ctx context.Context, in *TripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_CreateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) SubmitBidOrOffer(ctx context.Context, in *BidOrOfferRequest, opts ...grpc.CallOption) (*BidOrOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidOrOfferResponse)
	err := c.cc.Invoke(ctx, TripService_SubmitBidOrOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AcceptOffer(ctx context.Context, in *AcceptOfferRequest, opts ...grpc.CallOption) (*AcceptOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptOfferResponse)
	err := c.cc.Invoke(ctx, TripService_AcceptOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_GetTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetActiveTrips(ctx context.Context, in *TripFilterRequest, opts ...grpc.CallOption) (*ListTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTripResponse)
	err := c.cc.Invoke(ctx, TripService_GetActiveTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AcceptTrip(ctx context.Context, in *AcceptTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_AcceptTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*CancelTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTripResponse)
	err := c.cc.Invoke(ctx, TripService_CancelTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CompleteTrip(ctx context.Context, in *CompleteTripRequest, opts ...grpc.CallOption) (*CompleteTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTripResponse)
	err := c.cc.Invoke(ctx, TripService_CompleteTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetBiddingSession(ctx context.Context, in *BiddingSessionFilterRequest, opts ...grpc.CallOption) (*BiddingSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BiddingSessionResponse)
	err := c.cc.Invoke(ctx, TripService_GetBiddingSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTripHistory(ctx context.Context, in *TripHistoryFilterRequest, opts ...grpc.CallOption) (*TripHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripHistoryResponse)
	err := c.cc.Invoke(ctx, TripService_GetTripHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) IsTripActive(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_IsTripActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CreateRating(ctx context.Context, in *RatingRequest, opts ...grpc.CallOption) (*RatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingResponse)
	err := c.cc.Invoke(ctx, TripService_CreateRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*RatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingResponse)
	err := c.cc.Invoke(ctx, TripService_GetRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListRating(ctx context.Context, in *ListRatingRequest, opts ...grpc.CallOption) (*ListRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRatingResponse)
	err := c.cc.Invoke(ctx, TripService_ListRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) DeleteRating(ctx context.Context, in *DeleteRatingRequest, opts ...grpc.CallOption) (*DeleteRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRatingResponse)
	err := c.cc.Invoke(ctx, TripService_DeleteRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*RatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingResponse)
	err := c.cc.Invoke(ctx, TripService_UpdateRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripServiceServer is the server API for TripService service.
// All implementations must embed UnimplementedTripServiceServer
// for forward compatibility.
type TripServiceServer interface {
	// Trips
	CreateTrip(context.Context, *TripRequest) (*TripResponse, error)
	SubmitBidOrOffer(context.Context, *BidOrOfferRequest) (*BidOrOfferResponse, error)
	AcceptOffer(context.Context, *AcceptOfferRequest) (*AcceptOfferResponse, error)
	GetTrip(context.Context, *GetTripRequest) (*TripResponse, error)
	GetActiveTrips(context.Context, *TripFilterRequest) (*ListTripResponse, error)
	AcceptTrip(context.Context, *AcceptTripRequest) (*TripResponse, error)
	CancelTrip(context.Context, *CancelTripRequest) (*CancelTripResponse, error)
	CompleteTrip(context.Context, *CompleteTripRequest) (*CompleteTripResponse, error)
	// Bidding Session
	GetBiddingSession(context.Context, *BiddingSessionFilterRequest) (*BiddingSessionResponse, error)
	//Trip History
	GetTripHistory(context.Context, *TripHistoryFilterRequest) (*TripHistoryResponse, error)
	IsTripActive(context.Context, *GetTripRequest) (*TripResponse, error)
	//Rating
	CreateRating(context.Context, *RatingRequest) (*RatingResponse, error)
	GetRating(context.Context, *GetRatingRequest) (*RatingResponse, error)
	ListRating(context.Context, *ListRatingRequest) (*ListRatingResponse, error)
	DeleteRating(context.Context, *DeleteRatingRequest) (*DeleteRatingResponse, error)
	UpdateRating(context.Context, *UpdateRatingRequest) (*RatingResponse, error)
	mustEmbedUnimplementedTripServiceServer()
}

// UnimplementedTripServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTripServiceServer struct{}

func (UnimplementedTripServiceServer) CreateTrip(context.Context, *TripRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrip not implemented")
}
func (UnimplementedTripServiceServer) SubmitBidOrOffer(context.Context, *BidOrOfferRequest) (*BidOrOfferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBidOrOffer not implemented")
}
func (UnimplementedTripServiceServer) AcceptOffer(context.Context, *AcceptOfferRequest) (*AcceptOfferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptOffer not implemented")
}
func (UnimplementedTripServiceServer) GetTrip(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrip not implemented")
}
func (UnimplementedTripServiceServer) GetActiveTrips(context.Context, *TripFilterRequest) (*ListTripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveTrips not implemented")
}
func (UnimplementedTripServiceServer) AcceptTrip(context.Context, *AcceptTripRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptTrip not implemented")
}
func (UnimplementedTripServiceServer) CancelTrip(context.Context, *CancelTripRequest) (*CancelTripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTrip not implemented")
}
func (UnimplementedTripServiceServer) CompleteTrip(context.Context, *CompleteTripRequest) (*CompleteTripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTrip not implemented")
}
func (UnimplementedTripServiceServer) GetBiddingSession(context.Context, *BiddingSessionFilterRequest) (*BiddingSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBiddingSession not implemented")
}
func (UnimplementedTripServiceServer) GetTripHistory(context.Context, *TripHistoryFilterRequest) (*TripHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTripHistory not implemented")
}
func (UnimplementedTripServiceServer) IsTripActive(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsTripActive not implemented")
}
func (UnimplementedTripServiceServer) CreateRating(context.Context, *RatingRequest) (*RatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRating not implemented")
}
func (UnimplementedTripServiceServer) GetRating(context.Context, *GetRatingRequest) (*RatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRating not implemented")
}
func (UnimplementedTripServiceServer) ListRating(context.Context, *ListRatingRequest) (*ListRatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRating not implemented")
}
func (UnimplementedTripServiceServer) DeleteRating(context.Context, *DeleteRatingRequest) (*DeleteRatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRating not implemented")
}
func (UnimplementedTripServiceServer) UpdateRating(context.Context, *UpdateRatingRequest) (*RatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRating not implemented")
}
func (UnimplementedTripServiceServer) mustEmbedUnimplementedTripServiceServer() {}
func (UnimplementedTripServiceServer) testEmbeddedByValue()                     {}

// UnsafeTripServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripServiceServer will
// result in compilation errors.
type UnsafeTripServiceServer interface {
	mustEmbedUnimplementedTripServiceServer()
}

func RegisterTripServiceServer(s grpc.ServiceRegistrar, srv TripServiceServer) {
	// If the following call panics, it indicates UnimplementedTripServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TripService_ServiceDesc, srv)
}

func _TripService_CreateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CreateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CreateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CreateTrip(ctx, req.(*TripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_SubmitBidOrOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidOrOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).SubmitBidOrOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_SubmitBidOrOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).SubmitBidOrOffer(ctx, req.(*BidOrOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AcceptOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AcceptOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AcceptOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AcceptOffer(ctx, req.(*AcceptOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTrip(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetActiveTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetActiveTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetActiveTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetActiveTrips(ctx, req.(*TripFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AcceptTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AcceptTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AcceptTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AcceptTrip(ctx, req.(*AcceptTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CancelTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CancelTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CancelTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CancelTrip(ctx, req.(*CancelTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CompleteTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CompleteTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CompleteTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CompleteTrip(ctx, req.(*CompleteTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetBiddingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BiddingSessionFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetBiddingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetBiddingSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetBiddingSession(ctx, req.(*BiddingSessionFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTripHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripHistoryFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTripHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTripHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTripHistory(ctx, req.(*TripHistoryFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_IsTripActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).IsTripActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_IsTripActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).IsTripActive(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CreateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CreateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CreateRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CreateRating(ctx, req.(*RatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetRating(ctx, req.(*GetRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListRating(ctx, req.(*ListRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_DeleteRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).DeleteRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_DeleteRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).DeleteRating(ctx, req.(*DeleteRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_UpdateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).UpdateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_UpdateRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).UpdateRating(ctx, req.(*UpdateRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TripService_ServiceDesc is the grpc.ServiceDesc for TripService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrip",
			Handler:    _TripService_CreateTrip_Handler,
		},
		{
			MethodName: "SubmitBidOrOffer",
			Handler:    _TripService_SubmitBidOrOffer_Handler,
		},
		{
			MethodName: "AcceptOffer",
			Handler:    _TripService_AcceptOffer_Handler,
		},
		{
			MethodName: "GetTrip",
			Handler:    _TripService_GetTrip_Handler,
		},
		{
			MethodName: "GetActiveTrips",
			Handler:    _TripService_GetActiveTrips_Handler,
		},
		{
			MethodName: "AcceptTrip",
			Handler:    _TripService_AcceptTrip_Handler,
		},
		{
			MethodName: "CancelTrip",
			Handler:    _TripService_CancelTrip_Handler,
		},
		{
			MethodName: "CompleteTrip",
			Handler:    _TripService_CompleteTrip_Handler,
		},
		{
			MethodName: "GetBiddingSession",
			Handler:    _TripService_GetBiddingSession_Handler,
		},
		{
			MethodName: "GetTripHistory",
			Handler:    _TripService_GetTripHistory_Handler,
		},
		{
			MethodName: "IsTripActive",
			Handler:    _TripService_IsTripActive_Handler,
		},
		{
			MethodName: "CreateRating",
			Handler:    _TripService_CreateRating_Handler,
		},
		{
			MethodName: "GetRating",
			Handler:    _TripService_GetRating_Handler,
		},
		{
			MethodName: "ListRating",
			Handler:    _TripService_ListRating_Handler,
		},
		{
			MethodName: "DeleteRating",
			Handler:    _TripService_DeleteRating_Handler,
		},
		{
			MethodName: "UpdateRating",
			Handler:    _TripService_UpdateRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip/trip.proto",
}
